#!/usr/bin/env python3
"""
08_provenance_check.py -- provenance verifiability check for reused data.

Background: outputs/boundary_research/ in the old project was generated by an earlier AI assistant.
This script does **not trust** that directory's reports, maps or candidate lines; it only treats the raw
downloads as "bytes already saved locally" and tests with two kinds of independent evidence whether they are genuine official products:

  Evidence A (internal consistency): structure, units, quality flags and request parameters of the raw JSON/CSV;
                     unit conversions recomputed independently.
  Evidence B (cross-check): record-by-record comparison with the **separate, independent download** of 2026-03 in the old project.
                   The two downloads used different workflows, times and units;
                   if they agree record by record, the data are very likely genuine official products.

Parts that cannot be verified are recorded as such; no inference is made.
"""
import os, sys, json, datetime
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import paths as PTH
import numpy as np
import pandas as pd

OLD = PTH.OLD
NEW = PTH.ROOT
BR = PTH.OLD_BR
FT = 0.3048


def main():
    out = dict(
        generated_utc=datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ'),
        premise=('outputs/boundary_research/ was generated by an earlier AI assistant; '
                 'this project reuses only its raw downloaded bytes, not its reports/maps/candidate lines; '
                 'its terrain maps are not evidence that the NAVD88 conversion was done'),
        network_status=('the egress policy of this session returns 403 for waterservices.usgs.gov, '
                        'api.tidesandcurrents.noaa.gov etc.; '
                        'downloads cannot be re-run to verify the request parameters directly'),
        checks=[])

    # ---------------- NOAA 8720218
    j = json.load(open(os.path.join(BR, 'noaa/8720218_water_level_raw.json')))
    md = json.load(open(os.path.join(BR, 'noaa/8720218_metadata.json')))
    st = md['stations'][0]
    datums = {d['name']: d['value'] for d in st['datums']['datums']}
    msl_navd_m = (datums['MSL'] - datums['NAVD88']) * FT

    new = pd.DataFrame([(pd.Timestamp(r['t'], tz='UTC'), float(r['v']))
                        for r in j['data']], columns=['t', 'navd_m'])
    old = pd.read_csv(os.path.join(OLD, 'data/mayport_water_level.csv'))
    old['t'] = pd.to_datetime(old['Date'] + ' ' + old['Time (GMT)'], utc=True)
    old['ver_ft'] = pd.to_numeric(old['Verified (ft)'], errors='coerce')
    old['pred_ft'] = pd.to_numeric(old['Predicted (ft)'], errors='coerce')
    m = new.merge(old[['t', 'ver_ft', 'pred_ft']].dropna(subset=['ver_ft']), on='t')
    d = m.navd_m - m.ver_ft * FT
    dp = (m.navd_m - m.pred_ft * FT).dropna()

    out['checks'].append(dict(
        item='NOAA CO-OPS 8720218 Mayport water level',
        reused_file='outputs/boundary_research/noaa/8720218_water_level_raw.json',
        independent_file='data/mayport_water_level.csv (downloaded 2026-03, unit ft)',
        n_overlap=int(len(m)),
        diff_median_m=round(float(d.median()), 6),
        diff_std_m=round(float(d.std()), 6),
        diff_absmax_m=round(float(d.abs().max()), 6),
        verdict='verified compliant -- the two independent downloads agree record by record; differences are only 0.01 ft rounding noise',
        datum_evidence=dict(
            station_orthometric_datum=st['datums']['OrthometricDatum'],
            epoch=st['datums']['epoch'],
            msl_minus_navd88_m=round(msl_navd_m, 4),
            note=('median difference between old and new download is %.4f m, not %.4f m, '
                  'so the old ft series is itself already NAVD88; both share the same datum'
                  % (d.median(), msl_navd_m))),
        is_total_water_level=dict(
            diff_vs_astronomical_prediction_median_m=round(float(dp.median()), 4),
            diff_vs_prediction_std_m=round(float(dp.std()), 4),
            verdict='clearly different from the astronomical tide prediction; indeed observed total water level including meteorological surge')))

    # ---------------- USGS 02246500 parameter 63160 (independent copy available)
    c = pd.read_csv(os.path.join(OLD, 'data/usgs_city_water_level.csv'))
    c = c[c.parameter_code == 63160].copy()
    c['t'] = pd.to_datetime(c.time, utc=True)
    e = pd.read_csv(os.path.join(BR, 'usgs/02246500_63160.csv'))
    e['t'] = pd.to_datetime(e.timestamp_utc, utc=True)
    mm = c[['t', 'value', 'approval_status']].merge(
        e[['t', 'value_original', 'qualifiers']], on='t')
    out['checks'].append(dict(
        item='USGS 02246500 parameter 63160 (NAVD88 water level, used for same-source cross-check)',
        reused_file='outputs/boundary_research/usgs/02246500_63160.csv',
        independent_file='data/usgs_city_water_level.csv (downloaded 2026-03)',
        n_overlap=int(len(mm)),
        max_abs_diff=float(np.nanmax(np.abs(mm.value - mm.value_original)))
        if len(mm) else None,
        approval_status=dict(mm.approval_status.value_counts()),
        qualifiers=dict(mm.qualifiers.astype(str).value_counts()),
        verdict='verified compliant -- identical record by record'))

    # ---------------- USGS 02246500 parameter 00060 (actually used in this project; no independent copy)
    q = pd.read_csv(os.path.join(BR, 'usgs/02246500_00060.csv'))
    recomputed = q.value_original * 0.028316846592
    out['checks'].append(dict(
        item='USGS 02246500 parameter 00060 signed total discharge, tide not removed (actually used in this project)',
        reused_file='outputs/boundary_research/usgs/02246500_00060.csv',
        independent_file=None,
        n_records=int(len(q)),
        unit_conversion_recheck_max_dev_m3s=float(
            np.nanmax(np.abs(recomputed - q.value_si))),
        qualifiers=dict(q.qualifiers.astype(str).value_counts()),
        sign_kept=bool((q.value_original < 0).any()),
        negative_records=int((q.value_original < 0).sum()),
        verdict='usable with conditions',
        limitation=('The old project has no second independent download of 00060, so **no cross-check is possible**. '
                    'What can be confirmed: (1) unit conversion recomputed independently agrees (max deviation <1e-12); '
                    '(2) quality flags kept record by record; (3) 63160 produced by the same directory and download workflow '
                    'is identical to the independent copy, indirectly supporting that workflow; '
                    '(4) values look like a tidal station (signed, alternating sign). '
                    'Full confirmation requires re-downloading and comparing when the network is available.')))

    # ---------------- MRMS raw grib2 (not part of the AI directory)
    out['checks'].append(dict(
        item='MRMS GaugeCorr_QPE_01H raw grib2',
        reused_file='data/mrms_raw_old/*.grib2 (downloaded 2026-03, not the AI directory)',
        independent_file=None,
        verdict='verified compliant',
        evidence=('decoded directly from binary by the GRIB2 parser written for this project, '
                  'without any intermediate product: section 1 reference times match file names one by one (240/240), '
                  'section 3 grid is the standard MRMS CONUS 7000x3500 @0.01 deg, '
                  'section 5 is DRT template 41 (PNG), R=-30/E=0/D=1, '
                  'decoded value range matches the MRMS convention (-3 = no coverage)')))

    # ---------------- content explicitly not reused
    out['not_reused'] = [
        dict(path='outputs/boundary_research/proposed_boundary_locations.geojson',
             reason='old candidate boundary suggestions based on the old task setup; this project re-identifies '
                    'candidate boundaries from terrain connectivity; not used'),
        dict(path='outputs/boundary_research/proposed_boundary_map_zh.png/.svg',
             reason='old maps, not accepted deliverables'),
        dict(path='outputs/boundary_research/Jacksonville_Irma_boundary_research_zh.md',
             reason='AI-generated analysis report; read as background only, not as factual evidence'),
        dict(path='outputs/boundary_research/terrain_figure/*',
             reason='old terrain map; not evidence that the NAVD88 vertical conversion was done'),
        dict(path='outputs/boundary_research/usgs/02246500_72137.csv',
             reason='tidally filtered discharge; this task explicitly requires the un-detided 00060'),
        dict(path='data/mrms_qpe_jax/mrms_gaugeCorr_qpe1h_jax_26917.nc',
             reason='rainfall already reprojected to EPSG:26917, violating the requirement "keep the original ~1 km spatial '
                    'information, no default interpolation"; re-decoded from raw grib2 instead'),
        dict(path='data/dem_1_3arc_10m.tif / dem_study_area.tif / hu10_clip.tif',
             reason='1/3 arc-second (~10 m) DEM; this task explicitly requires the ~30 m 1 arc-second product'),
        dict(path='jacksonville_sfincs_input/* and QGIS/hu8_study_area/*',
             reason='grid, mask and boundaries of the old large HU8 domain; inconsistent with the two-HUC10 '
                    'study area of this task'),
    ]

    p = os.path.join(PTH.IRMA['meta'], 'provenance_check.json')
    with open(p, 'w') as f:
        json.dump(out, f, indent=1, ensure_ascii=False, default=str)
    for c_ in out['checks']:
        print(f"--- {c_['item']}\n    verdict: {c_['verdict']}")
        if c_.get('n_overlap') is not None:
            print(f"    overlap {c_['n_overlap']} records, median diff "
                  f"{c_.get('diff_median_m', c_.get('max_abs_diff'))}")
        if c_.get('limitation'):
            print(f"    limitation: {c_['limitation'][:90]}...")
    print('\nwritten', p)


if __name__ == '__main__':
    main()
