#!/usr/bin/env python3
"""
16_build_sfincs.py -- translate the prepared data into SFINCS native input files (200 m computational grid)

Output directory: Flood_2.0/sfincs_200m/
  sfincs.inp                 main control file (grid, time, physical parameters, file list)
  sfincs.ind / .msk / .dep   computational grid index / mask / bed elevation (binary, inputformat = bin)
  sfincs.bnd / .bzs          water-level boundary point coordinates / water-level time series (Mayport native 6 min)
  sfincs.src / .dis          discharge source point coordinates / discharge time series (Acosta native 15 min, split by cross-section)
  sfincs.ampr                spatial rainfall (Delft3D meteo ASCII, 1 km equidistant UTM grid, MRMS nearest-neighbour values)
  sfincs.precip              areal-mean rainfall (alternative for uniform rainfall, not enabled in inp)
  sfincs.obs                 observation points (9 stations, for his output)
  qgis/                      200 m dep / msk GeoTIFFs, boundary / source / observation point GeoJSON -- for checking in QGIS
  alt/                       hourly-mean versions of bzs / dis (alternative)
  sfincs_build.json          machine-readable record (resampling statistics, edge closure, source splitting, per-file checks)

Conventions:
  * Binary layout follows hydromt_sfincs: array (nmax, mmax), n=1 is south; flattened in column-major order, only active cells written.
  * tref = tstart = window start 2017-09-06 00:00 UTC; all time series are given as "seconds since tref".
  * Hourly rainfall accumulation P(T) represents [T-1h, T), written as mm/hr at the interval start T-1h (forward blocks), with one extra record at the end.
  * Roughness: three keywords manning_land / manning_sea + rgh_lev_land, no manningfile.
This script does not run SFINCS; none of the files have been validated by SFINCS itself -- see 'not_validated' in sfincs_build.json.
"""
import os, sys, json, datetime, shutil, importlib.util
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import paths as PTH
import geoio
import window_config as WCFG
import numpy as np
import pandas as pd

NEW = PTH.ROOT
GIS, PROC = PTH.STATIC_GIS, PTH.IRMA['processed']
INT, META = PTH.STATIC_INTERIM, PTH.STATIC_META
# Terrain 60 m -> 200 m fixed to block averaging (v1). The hybrid resampling scheme was rejected by the user on 2026-09-15; the related code has been removed.
DEP_RESAMPLE = 'mean'
OUT = PTH.SFINCS_BASE                    # static: dep/msk/ind/bnd/src/obs/inp
FORC = PTH.IRMA['forcing']                # event: bzs/dis/ampr/precip
QG, ALT = os.path.join(OUT, 'qgis'), os.path.join(FORC, 'alt')
for d in (OUT, QG, ALT, FORC):
    os.makedirs(d, exist_ok=True)

# ---------------- settings decided by the user ----------------
DX200 = 200.0
MANNING_LAND, MANNING_SEA, RGH_LEV_LAND = 0.06, 0.02, 0.0   # set by the user 2026-09-14
ACTIVE_FRAC = 0.5            # share of active 60 m cells within a 200 m cell >= this value -> active
QINF = 0.0                   # constant infiltration mm/hr -- default 0, flagged separately in the report for the user's attention
ADVECTION = 1
ALPHA, THETA, HUTHRESH = 0.5, 1.0, 0.05   # documented defaults
DTOUT, DTHISOUT = 3600, 600
BND_SPACING_M = 2000.0
ZONE = 17
EPSG = 26917

ext = json.load(open(os.path.join(META, 'study_extent.json')))
R = ext['rect_aligned']
X0, Y0 = R['xmin'], R['ymin']
MMAX = int(round((R['xmax'] - R['xmin']) / DX200))
NMAX = int(round((R['ymax'] - R['ymin']) / DX200))
assert abs(X0 + MMAX * DX200 - R['xmax']) < 1e-6 and abs(Y0 + NMAX * DX200 - R['ymax']) < 1e-6
print('SFINCS grid: mmax=%d nmax=%d dx=dy=%.0f m origin (%.0f, %.0f) EPSG:%d' % (MMAX, NMAX, DX200, X0, Y0, EPSG))

T0, T1, TSPIN, LABELS = WCFG.pd_window(pd)
TREF = T0
def secs(t):
    return (t - TREF) / pd.Timedelta('1s')

rec = dict(generated_utc=datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ'),
           not_validated='All files in this directory were generated by script following the SFINCS documentation format and have not yet been run with the SFINCS executable; '
                         'on first run, check sfincs.log to confirm the grid / boundaries / rainfall were read correctly',
           grid=dict(mmax=MMAX, nmax=NMAX, dx=DX200, dy=DX200, x0=X0, y0=Y0, rotation=0.0, epsg=EPSG),
           window=dict(tref=str(TREF), tstart=str(T0), tstop=str(T1), spinup_until=str(TSPIN)),
           settings=dict(manning_land=MANNING_LAND, manning_sea=MANNING_SEA,
                         rgh_lev_land=RGH_LEV_LAND, qinf=QINF, advection=ADVECTION,
                         alpha=ALPHA, theta=THETA, huthresh=HUTHRESH,
                         dep_resample=DEP_RESAMPLE, active_frac=ACTIVE_FRAC))

# ================= 1. 60 m -> 200 m =================
z60 = np.load(os.path.join(INT, 'merged60.npy'))            # (650, 850), row 0 = north
act60 = np.load(os.path.join(INT, 'active_mask.npy'))
ny60, nx60 = z60.shape
xc = R['xmin'] + (np.arange(nx60) + 0.5) * 60.0
yc = R['ymax'] - (np.arange(ny60) + 0.5) * 60.0
mi = np.floor((xc - X0) / DX200).astype(int)                # each 60 m column -> m (0-based)
ni = np.floor((yc - Y0) / DX200).astype(int)                # each 60 m row -> n (0-based, south=0)
MI, NI = np.meshgrid(mi, ni)
flat = NI.ravel() * MMAX + MI.ravel()
cnt = np.bincount(flat, minlength=NMAX * MMAX).astype(float)
zsum = np.bincount(flat, weights=z60.ravel(), minlength=NMAX * MMAX)
asum = np.bincount(flat, weights=act60.ravel().astype(float), minlength=NMAX * MMAX)
zmin = np.full(NMAX * MMAX, np.inf)
np.minimum.at(zmin, flat, z60.ravel())
wsum = np.bincount(flat, weights=(z60.ravel() <= 0).astype(float), minlength=NMAX * MMAX)

Zmean = (zsum / np.maximum(cnt, 1)).reshape(NMAX, MMAX)     # (nmax, mmax), n=0 is south
Zmin = zmin.reshape(NMAX, MMAX)
FRAC = (asum / np.maximum(cnt, 1)).reshape(NMAX, MMAX)
WFRAC = (wsum / np.maximum(cnt, 1)).reshape(NMAX, MMAX)
CNT = cnt.reshape(NMAX, MMAX)
Z = Zmean                                                   # block average (v1)
ACT = FRAC >= ACTIVE_FRAC
print('60 m cells per 200 m cell = %.1f (min %d max %d)' % (CNT.mean(), CNT.min(), CNT.max()))

rec['resample'] = dict(
    cells_per_200m_cell=dict(mean=float(CNT.mean()), min=int(CNT.min()), max=int(CNT.max())),
    active_200m_cells=int(ACT.sum()),
    active_200m_km2=round(float(ACT.sum()) * DX200 * DX200 / 1e6, 2),
    active_60m_km2=round(float(act60.sum()) * 3600 / 1e6, 2),
    water_60m_cells_in_active=int((act60 & (z60 <= 0)).sum()),
    water_200m_cells_mean=int((ACT & (Zmean <= 0)).sum()),
    water_200m_cells_min=int((ACT & (Zmin <= 0)).sum()),
    water_area_km2_60m=round(float((act60 & (z60 <= 0)).sum()) * 3600 / 1e6, 2),
    water_area_km2_200m_mean=round(float((ACT & (Zmean <= 0)).sum()) * DX200 ** 2 / 1e6, 2),
    water_area_km2_200m_min=round(float((ACT & (Zmin <= 0)).sum()) * DX200 ** 2 / 1e6, 2),
    z_range_200m=[round(float(Z[ACT].min()), 2), round(float(Z[ACT].max()), 2)])
print('active cells %d (%.1f km2); water cells (z<=0) 60 m version %.1f km2 -> 200 m mean version %.1f km2 / min version %.1f km2'
      % (ACT.sum(), rec['resample']['active_200m_km2'], rec['resample']['water_area_km2_60m'],
         rec['resample']['water_area_km2_200m_mean'], rec['resample']['water_area_km2_200m_min']))

# ================= 2. boundary lines -> 200 m cells =================
def gj_lines(path):
    d = json.load(open(path)); out = []
    for f in d['features']:
        g = f['geometry']
        if not g or not g.get('coordinates'):
            continue
        segs = [g['coordinates']] if g['type'] == 'LineString' else g['coordinates']
        pts = []
        for s in segs:
            a = np.asarray(s, float)
            x, y = geoio.ll_to_utm(a[:, 0], a[:, 1], ZONE)
            pts.append(np.c_[x, y])
        out.append((np.vstack(pts), f['properties']))
    return out


def densify(p, step=25.0):
    o = [p[0]]
    for a, b in zip(p[:-1], p[1:]):
        n = max(1, int(np.ceil(float(np.hypot(*(b - a))) / step)))
        for k in range(1, n + 1):
            o.append(a + (b - a) * (k / n))
    return np.array(o)


def cells_of(pts):
    p = densify(pts)
    m = np.floor((p[:, 0] - X0) / DX200).astype(int)
    n = np.floor((p[:, 1] - Y0) / DX200).astype(int)
    ok = (m >= 0) & (m < MMAX) & (n >= 0) & (n < NMAX)
    seen, out = set(), []
    for a, b in zip(n[ok], m[ok]):
        if (a, b) not in seen:
            seen.add((a, b)); out.append((a, b))
    return out


MSK = np.where(ACT, 1, 0).astype(np.uint8)
DWL = gj_lines(os.path.join(GIS, 'bnd_downstream_waterlevel.geojson'))
UPL = gj_lines(os.path.join(GIS, 'bnd_upstream_discharge.geojson'))

# active-domain edge cells (at least one of the four neighbours inactive)
_pad = np.zeros((NMAX + 2, MMAX + 2), bool); _pad[1:-1, 1:-1] = ACT
EDGE = ACT & ~(_pad[:-2, 1:-1] & _pad[2:, 1:-1] & _pad[1:-1, :-2] & _pad[1:-1, 2:])


def grow(cells):
    out = set()
    for n, m in cells:
        for dn in (-1, 0, 1):
            for dm in (-1, 0, 1):
                a, b = n + dn, m + dm
                if 0 <= a < NMAX and 0 <= b < MMAX:
                    out.add((a, b))
    return out


# The 60 m boundary lines "straddle cells" on the 200 m grid: if a cell crossed by the line is inactive (e.g. more than half seaward), the
# water-level boundary is placed on the active edge cells within its 8-neighbourhood, so that coast / estuary boundaries stay continuous at 200 m.
bnd_cells, bnd_info = [], []
for pts, p in DWL:
    cs = cells_of(pts)
    on = [(n, m) for (n, m) in cs if ACT[n, m]]
    nb = [(n, m) for (n, m) in grow(cs) if ACT[n, m] and EDGE[n, m] and (n, m) not in set(on)]
    for n, m in on + nb:
        MSK[n, m] = 2
    bnd_cells += on + nb
    zz = [Z[n, m] for n, m in on + nb]
    bnd_info.append(dict(bnd_id=p['bnd_id'], line_cells=len(cs), line_cells_active=len(on),
                         neighbour_edge_cells_added=len(nb), msk2_cells=len(on) + len(nb),
                         z_min_200m=round(float(min(zz)), 2) if zz else None))
    print('  %s: line crosses %d 200 m cells (%d active) + %d neighbouring edge cells -> msk=2 total %d'
          % (p['bnd_id'], len(cs), len(on), len(nb), len(on) + len(nb)))

# Boundary points: one point every BND_SPACING_M along the DW lines (all pointing to the same Mayport series)
bnd_pts = []
for pts, p in DWL:
    d = densify(pts, 5.0)
    seg = np.hypot(*(d[1:] - d[:-1]).T)
    s = np.concatenate([[0], np.cumsum(seg)])
    L = s[-1]
    nn = max(2, int(np.floor(L / BND_SPACING_M)) + 1)
    for t in np.linspace(0, L, nn):
        k = int(np.searchsorted(s, t))
        k = min(k, len(d) - 1)
        bnd_pts.append((float(d[k, 0]), float(d[k, 1]), p['bnd_id']))
print('  water-level boundary points: %d' % len(bnd_pts))

# Source points: active water cells crossed by UP01, split by (-z * dx)
src_pts = []
for pts, p in UPL:
    cs0 = cells_of(pts)
    cs = [(n, m) for (n, m) in cs0 if ACT[n, m]]
    # likewise merge active water cells on the domain edge within the line's 8-neighbourhood into the source cells (at 200 m the channel section is wider than the cells crossed by the line)
    nb = [(n, m) for (n, m) in grow(cs0) if ACT[n, m] and EDGE[n, m] and Z[n, m] <= 0
          and (n, m) not in set(cs)]
    wet = [(n, m) for (n, m) in cs if Z[n, m] <= 0] + nb
    if not wet:
        wet = [min(cs, key=lambda c: Z[c])]
    w = np.array([max(-Z[n, m], 0.05) for n, m in wet]) * DX200
    w = w / w.sum() * p.get('Q_fraction', 1.0)
    for (n, m), f in zip(wet, w):
        src_pts.append(dict(x=X0 + (m + 0.5) * DX200, y=Y0 + (n + 0.5) * DX200, n=n, m=m,
                            z=round(float(Z[n, m]), 2), frac=round(float(f), 4), bnd_id=p['bnd_id']))
    print('  %s: line crosses %d active cells + %d neighbouring edge water cells -> %d source cells, split by section: %s'
          % (p['bnd_id'], len(cs), len(nb), len(wet), ', '.join('%.1f%%' % (s['frac'] * 100) for s in src_pts)))
rec['boundaries'] = dict(waterlevel=bnd_info, n_msk2=int((MSK == 2).sum()),
                         n_bnd_points=len(bnd_pts), bnd_spacing_m=BND_SPACING_M,
                         sources=src_pts, q_fraction_sum=round(float(sum(s['frac'] for s in src_pts)), 4))

# Cells on the 200 m active-domain edge that are "water but neither msk=2 nor a source point" (default wall)
edge = EDGE
srcset = {(s['n'], s['m']) for s in src_pts}
open_wall = [(n, m) for n, m in zip(*np.where(edge & (Z <= 0) & (MSK != 2))) if (n, m) not in srcset]
rec['boundaries']['wall_water_edge_cells_200m'] = len(open_wall)
print('  200 m domain-edge water cells without a boundary (wall): %d' % len(open_wall))

# ================= 3. binary grid files =================
def write_bin_grid():
    mt = MSK.T                                            # (mmax, nmax)
    ind = np.where(mt.flatten() > 0)[0]                   # column-major: m outer, n inner
    np.array(np.hstack([[len(ind)], ind + 1]), dtype='<u4').tofile(os.path.join(OUT, 'sfincs.ind'))
    np.asarray(mt.flatten()[ind], dtype='u1').tofile(os.path.join(OUT, 'sfincs.msk'))
    np.asarray(Z.T.flatten()[ind], dtype='<f4').tofile(os.path.join(OUT, 'sfincs.dep'))
    return len(ind)

n_active_written = write_bin_grid()

# read back for self-check
def read_bin_grid():
    ind = np.fromfile(os.path.join(OUT, 'sfincs.ind'), dtype='<u4')
    n = int(ind[0]); ind = ind[1:1 + n] - 1
    msk = np.fromfile(os.path.join(OUT, 'sfincs.msk'), dtype='u1')
    dep = np.fromfile(os.path.join(OUT, 'sfincs.dep'), dtype='<f4')
    M = np.zeros(MMAX * NMAX, np.uint8); D = np.full(MMAX * NMAX, np.nan, np.float32)
    M[ind] = msk; D[ind] = dep
    return M.reshape(MMAX, NMAX).T, D.reshape(MMAX, NMAX).T, n

M2, D2, n2 = read_bin_grid()
assert n2 == n_active_written == int(ACT.sum())
assert np.array_equal(M2, MSK)
assert np.allclose(np.where(ACT, Z, np.nan), D2, equal_nan=True, atol=1e-5)
rec['binary_roundtrip'] = dict(active_written=n2, msk_identical=True, dep_max_abs_diff=float(
    np.nanmax(np.abs(np.where(ACT, Z, np.nan) - D2))))
print('binary ind/msk/dep written and read back consistently, active cells %d' % n2)

# GeoTIFF for QGIS (north up)
tr200 = (X0, DX200, 0.0, Y0 + NMAX * DX200, 0.0, -DX200)
geoio.write_geotiff(os.path.join(QG, 'sfincs_dep_200m.tif'),
                    np.flipud(np.where(ACT, Z, -9999.0)).astype(np.float32), tr200, EPSG,
                    nodata=-9999.0, citation='SFINCS dep 200 m (m NAVD88), inactive=-9999')
geoio.write_geotiff(os.path.join(QG, 'sfincs_msk_200m.tif'),
                    np.flipud(MSK).astype(np.float32), tr200, EPSG, nodata=None,
                    citation='SFINCS msk 200 m: 0 inactive, 1 active, 2 water-level boundary')

# ================= 4. water level / discharge time series =================
wl = pd.read_csv(os.path.join(PROC, 'mayport_8720218_waterlevel_6min_utc_navd88_m.csv'))
wl['t'] = pd.to_datetime(wl.time_utc, utc=True)
wl = wl[(wl.t >= T0) & (wl.t <= T1)].dropna(subset=['water_level_m_navd88']).sort_values('t')
q = pd.read_csv(os.path.join(PROC, 'acosta_02246500_discharge_15min_utc_m3s.csv'))
q['t'] = pd.to_datetime(q.time_utc, utc=True)
q = q[(q.t >= T0) & (q.t <= T1)].dropna(subset=['discharge_m3s']).sort_values('t')

with open(os.path.join(OUT, 'sfincs.bnd'), 'w') as f:
    for x, y, _ in bnd_pts:
        f.write('%12.2f %13.2f\n' % (x, y))
ts = secs(wl.t).values; hv = wl.water_level_m_navd88.values
with open(os.path.join(FORC, 'sfincs.bzs'), 'w') as f:
    for t, h in zip(ts, hv):
        f.write('%10.1f' % t + ''.join(' %8.4f' % h for _ in bnd_pts) + '\n')
with open(os.path.join(OUT, 'sfincs.src'), 'w') as f:
    for s in src_pts:
        f.write('%12.2f %13.2f\n' % (s['x'], s['y']))
tq = secs(q.t).values; qv = q.discharge_m3s.values
with open(os.path.join(FORC, 'sfincs.dis'), 'w') as f:
    for t, Q in zip(tq, qv):
        f.write('%10.1f' % t + ''.join(' %10.3f' % (Q * s['frac']) for s in src_pts) + '\n')

# hourly-mean alternative
wlh = pd.read_csv(os.path.join(PROC, 'mayport_8720218_waterlevel_hourly_utc_navd88_m.csv'))
qh = pd.read_csv(os.path.join(PROC, 'acosta_02246500_discharge_hourly_utc_m3s.csv'))
with open(os.path.join(ALT, 'sfincs_hourly.bzs'), 'w') as f:
    for t, h in zip(pd.to_datetime(wlh.hour_end_utc, utc=True), wlh.water_level_m_navd88_hourly_mean):
        f.write('%10.1f' % (secs(t) - 1800) + ''.join(' %8.4f' % h for _ in bnd_pts) + '\n')
with open(os.path.join(ALT, 'sfincs_hourly.dis'), 'w') as f:
    for t, Q in zip(pd.to_datetime(qh.hour_end_utc, utc=True), qh.discharge_m3s_hourly_mean):
        f.write('%10.1f' % (secs(t) - 1800) + ''.join(' %10.3f' % (Q * s['frac']) for s in src_pts) + '\n')
rec['bzs'] = dict(source='Mayport native 6 min', records=len(ts), t_first_s=float(ts[0]),
                  t_last_s=float(ts[-1]), covers_run=bool(ts[0] <= 0 and ts[-1] >= secs(T1)),
                  h_range=[round(float(hv.min()), 3), round(float(hv.max()), 3)],
                  columns=len(bnd_pts), note='same series for all boundary points; hourly-mean version (placed at interval midpoints) under alt/')
rec['dis'] = dict(source='Acosta native 15 min, parameter 00060 signed', records=len(tq),
                  t_first_s=float(tq[0]), t_last_s=float(tq[-1]),
                  covers_run=bool(tq[0] <= 0 and tq[-1] >= secs(T1)),
                  q_range=[round(float(qv.min()), 1), round(float(qv.max()), 1)],
                  columns=len(src_pts), negative_fraction=round(float((qv < 0).mean()), 3))
print('bzs %d records (%.0f..%.0f s) | dis %d records (%.0f..%.0f s)' % (len(ts), ts[0], ts[-1], len(tq), tq[0], tq[-1]))

# ================= 5. rainfall =================
P = np.load(os.path.join(PTH.IRMA['raw'], 'mrms_cache/mrms_P.npy'))            # (240, 40, 57) row 0 = north
LL = np.load(os.path.join(PTH.IRMA['raw'], 'mrms_cache/mrms_lonlat.npy'))
lon_min, lon_max, lat_min, lat_max, dlon, dlat = LL
nlat, nlon = P.shape[1], P.shape[2]
lons = lon_min + np.arange(nlon) * abs(dlon)
lats = lat_max - np.arange(nlat) * abs(dlat)          # row 0 = north
n_nonfinite = int((~np.isfinite(P)).sum())
assert n_nonfinite == 0, 'MRMS cache contains %d non-finite values -- no filling, fix the data first' % n_nonfinite
P = np.clip(P, 0, None)

# ---- the rainfall grid (1 km) extends beyond the SFINCS model domain: 1 km west / east / south, 2 km north ----
# Based on runs/_tests/ampr_roworder (2026-09-15): SFINCS does not use row 1 of the ampr file (northernmost row) and does not extrapolate beyond the centre of the northernmost valid row;
# with a 1 km extension the northernmost 2 model rows (400 m) still got no rain (T2), so the north side is extended by one more row. All extended cells fall inside the MRMS cache and take real values; no zero-filling, no extrapolation.
DXR = 1000.0
RAIN_MARGIN = dict(w=1, e=1, s=1, n=2)                  # unit: number of 1 km cells
AX0, AX1 = R['xmin'] - RAIN_MARGIN['w'] * DXR, R['xmax'] + RAIN_MARGIN['e'] * DXR
AY0, AY1 = R['ymin'] - RAIN_MARGIN['s'] * DXR, R['ymax'] + RAIN_MARGIN['n'] * DXR
ncol, nrow = int(round((AX1 - AX0) / DXR)), int(round((AY1 - AY0) / DXR))
xr = AX0 + (np.arange(ncol) + 0.5) * DXR
yr = AY1 - (np.arange(nrow) + 0.5) * DXR                # row 0 = north
XR, YR = np.meshgrid(xr, yr)
LO, LA = geoio.utm_to_ll(XR.ravel(), YR.ravel(), ZONE)
ci_raw = np.round((LO - lons[0]) / abs(dlon)).astype(int)
ri_raw = np.round((lats[0] - LA) / abs(dlat)).astype(int)
inside_mask = (ci_raw >= 0) & (ci_raw < nlon) & (ri_raw >= 0) & (ri_raw < nlat)
inside = float(inside_mask.mean())
assert inside == 1.0, '%d cells of the extended rainfall grid fall outside the MRMS cache -- no extrapolation, enlarge the MRMS window first' % int((~inside_mask).sum())
ci, ri = ci_raw, ri_raw
PR = P[:, ri, ci].reshape(P.shape[0], nrow, ncol)      # (240, nrow, ncol) nearest neighbour
# self-check: every SFINCS active cell centre lies within the "valid coverage" of ampr (envelope of cell centres after removing file row 1)
_xc = X0 + (np.arange(MMAX) + 0.5) * DX200; _yc = Y0 + (np.arange(NMAX) + 0.5) * DX200
_XC, _YC = np.meshgrid(_xc, _yc)
_valid = (_XC >= xr[0]) & (_XC <= xr[-1]) & (_YC >= yr[-1]) & (_YC <= yr[1])   # yr[1] = centre of row 2 (row 1 is ignored by SFINCS)
_uncov = int((ACT & ~_valid).sum())
assert _uncov == 0, '%d active cell centres are not within the valid ampr coverage' % _uncov

t_rain = [secs(T - pd.Timedelta('1h')) for T in LABELS] + [secs(T1)]
PR_out = np.concatenate([PR, PR[-1:]], 0)
with open(os.path.join(FORC, 'sfincs.ampr'), 'w') as f:
    f.write('FileVersion      = 1.03\n')
    f.write('filetype         = meteo_on_equidistant_grid\n')
    f.write('NODATA_value     = -999\n')
    f.write('n_cols           = %d\n' % ncol)
    f.write('n_rows           = %d\n' % nrow)
    f.write('grid_unit        = m\n')
    f.write('x_llcorner       = %.1f\n' % AX0)
    f.write('y_llcorner       = %.1f\n' % AY0)
    f.write('dx               = %.1f\n' % DXR)
    f.write('dy               = %.1f\n' % DXR)
    f.write('n_quantity       = 1\n')
    f.write('quantity1        = precipitation\n')
    f.write('unit1            = mm/hr\n')
    # time reference is tref (not 1970): SFINCS computes tim*3600 in single precision; ~1.5e9 s since 1970 has only 128 s precision,
    # which shifts the hourly stamps by ±64 s, conflicting with the dtwnd update window and dropping / double-counting ramp segments (measured in runs/_tests T6-T12 on 2026-09-15, source sfincs_spiderweb.f90).
    for t, A in zip(t_rain, PR_out):
        f.write('TIME = %.4f hours since %s +00:00\n' % (t / 3600.0, TREF.strftime('%Y-%m-%d %H:%M:%S')))
        for row in A:                                     # first row = north
            f.write(' '.join('%.2f' % v for v in row) + '\n')
areal = P.reshape(P.shape[0], -1).mean(1)
with open(os.path.join(FORC, 'sfincs.precip'), 'w') as f:
    for t, v in zip(t_rain, np.concatenate([areal, areal[-1:]])):
        f.write('%10.1f %8.3f\n' % (t, v))
rec['rain'] = dict(spatial_file='sfincs.ampr', grid=dict(dx=DXR, ncol=ncol, nrow=nrow,
                   x_ll=AX0, y_ll=AY0, first_row='north', margin_cells=RAIN_MARGIN,
                   note='grid extends beyond the model domain (W/E/S 1 km, N 2 km); SFINCS does not use file row 1; all active cell centres are within the valid coverage (asserted)'),
                   active_cells_uncovered=_uncov, mrms_nonfinite=n_nonfinite,
                   method='MRMS 0.01 degree native cells -> 1 km UTM equidistant cells, nearest-neighbour values (no smoothing)',
                   mrms_coverage_of_grid=round(float(inside), 4),
                   time_convention='P(T) is the accumulation over [T-1h,T), placed as mm/hr at the interval start T-1h (consistent with the blocks of the SFINCS default ampr_block=1); one extra record at the end to cover up to tstop',
                   time_line='TIME = <hours since tref> (no 1970 reference, to avoid the SFINCS single-precision 128 s error)',
                   records=len(t_rain),
                   total_mm_mrms_mean=round(float(P.sum(0).mean()), 1),
                   total_mm_ampr_mean=round(float(PR.sum(0).mean()), 1),
                   uniform_fallback='sfincs.precip (areal mean, not enabled in inp)')
print('ampr: %dx%d @1 km, %d time steps; MRMS coverage %.1f%%; event total rain MRMS mean %.1f / ampr mean %.1f mm'
      % (ncol, nrow, len(t_rain), inside * 100, P.sum(0).mean(), PR.sum(0).mean()))

# ================= 6. observation points =================
spec = importlib.util.spec_from_file_location('s10', os.path.join(os.path.dirname(os.path.abspath(__file__)), '10_active_domain_boundaries.py'))
s10 = importlib.util.module_from_spec(spec); spec.loader.exec_module(s10)
obs = []
for st in [s10.ACOSTA, s10.MAYPORT] + s10.OTHER_STATIONS:
    x, y = geoio.ll_to_utm(st['lon'], st['lat'], ZONE)
    m, n = int((x - X0) // DX200), int((y - Y0) // DX200)
    inside_ = 0 <= m < MMAX and 0 <= n < NMAX
    act_ = bool(ACT[n, m]) if inside_ else False
    obs.append(dict(id=st['id'], name=st['name'], x=float(x), y=float(y), in_active=act_))
with open(os.path.join(OUT, 'sfincs.obs'), 'w') as f:
    for o in obs:
        f.write("%12.2f %13.2f  '%s'\n" % (o['x'], o['y'], o['id']))
rec['obs'] = obs
print('observation points: %d, in the active domain: %d' % (len(obs), sum(o['in_active'] for o in obs)))

# ================= 7. sfincs.inp =================
inp = [
    ('# ---- grid ----', None),
    ('mmax', MMAX), ('nmax', NMAX), ('dx', DX200), ('dy', DX200),
    ('x0', X0), ('y0', Y0), ('rotation', 0.0), ('epsg', EPSG), ('latitude', 30.35),
    ('# ---- time (UTC) ----', None),
    ('tref', TREF.strftime('%Y%m%d %H%M%S')),
    ('tstart', T0.strftime('%Y%m%d %H%M%S')),
    ('tstop', T1.strftime('%Y%m%d %H%M%S')),
    ('tspinup', 3600),
    ('dtout', DTOUT), ('dthisout', DTHISOUT), ('dtmaxout', int(secs(T1))),
    ('storecumprcp', 1),
    ('dtwnd', 60),
    ('# ---- physics and numerics ----', None),
    ('alpha', ALPHA), ('theta', THETA), ('huthresh', HUTHRESH),
    ('advection', ADVECTION),
    ('manning_land', MANNING_LAND), ('manning_sea', MANNING_SEA), ('rgh_lev_land', RGH_LEV_LAND),
    ('zsini', round(float(hv[0]), 3)),
    ('qinf', QINF),
    ('# ---- input files ----', None),
    ('inputformat', 'bin'), ('outputformat', 'net'),
    ('depfile', 'sfincs.dep'), ('mskfile', 'sfincs.msk'), ('indexfile', 'sfincs.ind'),
    ('bndfile', 'sfincs.bnd'), ('bzsfile', 'sfincs.bzs'),
    ('srcfile', 'sfincs.src'), ('disfile', 'sfincs.dis'),
    ('amprfile', 'sfincs.ampr'),
    ('obsfile', 'sfincs.obs'),
]
with open(os.path.join(OUT, 'sfincs.inp'), 'w') as f:
    for k, v in inp:
        if v is None:
            f.write(k + '\n')
        else:
            f.write('%-16s= %s\n' % (k, v))
rec['inp'] = {k: v for k, v in inp if v is not None}
rec['inp_note'] = dict(
    zsini='initial water level = Mayport observation at tstart; depressions below it are wet at t=0 and are absorbed by the 72 h spin-up',
    tspinup='SFINCS\'s own boundary ramp-up time (1 h), distinct from this project\'s 72 h analysis spin-up',
    dtmaxout='only one max water depth / level map for the whole window',
    storecumprcp='output cumulative rainfall cumprcp in the map, for reconciling with the ampr input in 21_rain_qc.py',
    dtwnd='meteo field update interval 60 s (default 1800): SFINCS interpolates linearly between adjacent frames; at 60 s the hourly amount ≈ 0.98 P_k + 0.02 P_k+1, close to blocks; at 1800 s it is 0.75/0.25',
    precip='inp enables amprfile (spatial rainfall); for uniform rainfall, replace amprfile with precipfile = sfincs.precip')

# QGIS helper vectors
G = geoio.GeoJSONWriter(QG, EPSG, ZONE)
def wkb_point(x, y):
    import struct
    return struct.pack('<BIdd', 1, 1, x, y)
G.add_layer('sfincs_bnd_points', 'POINT',
            [(wkb_point(x, y), None, dict(bnd_id=b, k=i)) for i, (x, y, b) in enumerate(bnd_pts)],
            [('bnd_id', 'TEXT'), ('k', 'INTEGER')], 'SFINCS water-level boundary points (bnd)')
G.add_layer('sfincs_src_points', 'POINT',
            [(wkb_point(s['x'], s['y']), None, dict(bnd_id=s['bnd_id'], q_frac=s['frac'], z_m=s['z']))
             for s in src_pts],
            [('bnd_id', 'TEXT'), ('q_frac', 'REAL'), ('z_m', 'REAL')], 'SFINCS discharge source points (src)')
G.add_layer('sfincs_obs_points', 'POINT',
            [(wkb_point(o['x'], o['y']), None, dict(station_id=o['id'], name=o['name'],
                                                     in_active=int(o['in_active']))) for o in obs],
            [('station_id', 'TEXT'), ('name', 'TEXT'), ('in_active', 'INTEGER')], 'SFINCS observation points (obs)')

np.save(os.path.join(INT, 'sfincs200_Z.npy'), Z)
np.save(os.path.join(INT, 'sfincs200_MSK.npy'), MSK)
np.save(os.path.join(INT, 'sfincs200_Zmin.npy'), Zmin)
np.save(os.path.join(INT, 'sfincs200_WFRAC.npy'), WFRAC)
def _np(o):
    if isinstance(o, (np.integer,)): return int(o)
    if isinstance(o, (np.floating,)): return float(o)
    if isinstance(o, (np.bool_,)): return bool(o)
    raise TypeError(str(type(o)))
rec['boundaries']['wall_water_edge_cells_200m_list'] = [
    dict(n=int(n), m=int(m), x=float(X0 + (m + .5) * DX200), y=float(Y0 + (n + .5) * DX200),
         z=round(float(Z[n, m]), 2)) for n, m in open_wall]
json.dump(rec, open(os.path.join(OUT, 'sfincs_build.json'), 'w'), ensure_ascii=False, indent=1, default=_np)
sizes = {f: os.path.getsize(os.path.join(OUT, f)) for f in sorted(os.listdir(OUT)) if os.path.isfile(os.path.join(OUT, f))}
print('\nOutput %s:' % OUT)
for k, v in sizes.items():
    print('  %-20s %10.1f KB' % (k, v / 1024))
