#!/usr/bin/env python3
"""55_final_tables_exp3.py -- Exp. 3 appendix tables (draft _v1, csv + md). Reads result files only; every number is read from a file, nothing is estimated.

Tables:
  tab_e3_strat_v1   stratified table: by compound forcing level (low / medium / high) and rainfall time shift τ (-6 / 0 / +6 h), single-step RMSE (active cells) of zero-shot / B N=5 / B N=10 and the reduction
  tab_e3_forget_v1   source-domain forgetting table: N × B / B' single-step RMSE (active cells) on the 50 test runs of the other 5 events, change relative to before fine-tuning, worst single-fold change
  tab_e3_attrs_v1  event attribute table: event, B N=5 reduction, Exp. 2 degradation factor, wetness (mean SFINCS land inundation area over the event's 10 test runs, km^2), total rainfall, rainfall product
Conventions (consistent with result/reports/exp3_report.md):
  "six-fold mean" for stratification and forgetting = each fold first pools the three seeds (already pooled in stratified.csv for the stratified table; averaged over seeds for the forgetting table), then the arithmetic mean over six folds;
  stratified reduction is computed from the six-fold means; forgetting change percentages are computed per fold then averaged over six folds, "worst fold" is the maximum over six folds (both as in exp3_report.md).
Sources: result/models/exp3/stratified.csv, source_forgetting.csv, correlates.csv, curve_by_fold.csv
Outputs: final_report_materials/tables/tab_e3_*_v1.{csv,md}
Usage: python3 code/55_final_tables_exp3.py
"""
import os, csv
import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'final_report_materials', 'tables')
EVENTS = ['irma', 'matthew', 'ian', 'milton', 'dorian', 'beryl']
EV_CN = dict(irma='Irma', matthew='Matthew', ian='Ian', milton='Milton', dorian='Dorian', beryl='Beryl')
NS = [1, 2, 3, 5, 10]
rcsv = lambda p: list(csv.DictReader(open(os.path.join(ROOT, p))))


def wcsv(name, cols, rows):
    with open(os.path.join(OUT, name + '.csv'), 'w', newline='') as f:
        w = csv.DictWriter(f, cols); w.writeheader(); w.writerows(rows)


def wmd(name, title, header, lines, notes):
    with open(os.path.join(OUT, name + '.md'), 'w') as f:
        f.write('# %s\n\n' % title)
        f.write('| ' + ' | '.join(header) + ' |\n|' + '---|' * len(header) + '\n')
        for ln in lines:
            f.write('| ' + ' | '.join(ln) + ' |\n')
        f.write('\nNotes:\n\n' + ''.join('- %s\n' % n for n in notes))


# ---------------------------------------------------------------- 1 stratified table
def stratified():
    S = [r for r in rcsv('result/models/exp3/stratified.csv') if r['mask'] == 'active']
    g = lambda f, by, grp, m, n: float(next(r['rmse'] for r in S if r['fold'] == f and r['by'] == by and r['group'] == grp and r['method'] == m and int(r['N']) == n))
    groups = [('level', 'low', 'Compound forcing level: low'), ('level', 'mid', 'Compound forcing level: medium'), ('level', 'high', 'Compound forcing level: high'),
              ('tau_h', '-6', 'Rainfall time shift τ = -6 h'), ('tau_h', '0', 'Rainfall time shift τ = 0'), ('tau_h', '6', 'Rainfall time shift τ = +6 h')]
    rows, lines = [], []
    for by, grp, cn in groups:
        z = np.array([g(f, by, grp, 'zero', 0) for f in EVENTS])
        b5 = np.array([g(f, by, grp, 'B', 5) for f in EVENTS]); b10 = np.array([g(f, by, grp, 'B', 10) for f in EVENTS])
        d5 = np.array([100 * (z.mean() - b5.mean()) / z.mean()]); d10 = np.array([100 * (z.mean() - b10.mean()) / z.mean()])
        rows.append(dict(stratum=cn, zero_rmse=round(z.mean(), 4), B_N5_rmse=round(b5.mean(), 4), B_N5_drop_pct=round(d5.mean(), 1),
                         B_N10_rmse=round(b10.mean(), 4), B_N10_drop_pct=round(d10.mean(), 1)))
        lines.append([cn, '%.4f' % z.mean(), '%.4f' % b5.mean(), '%.1f %%' % d5.mean(), '%.4f' % b10.mean(), '%.1f %%' % d10.mean()])
    wcsv('tab_e3_strat_v1', list(rows[0]), rows)
    wmd('tab_e3_strat_v1', 'Appendix table: Exp. 3 stratified results (single-step RMSE, active cells, six-fold mean)',
        ['Stratum', 'Zero-shot', 'B N=5', 'Reduction', 'B N=10', 'Reduction'], lines,
        ['The compound forcing level is defined by (α, β, γ) (low / medium / high, 27 scenarios each); the rainfall time shift τ is -6 / 0 / +6 h (27 scenarios each); each fold\'s test runs are assigned to their stratum.',
         'Each fold first pools the three seeds (`stratified.csv` is already pooled); "six-fold mean" is the arithmetic mean of the six fold RMSEs; reduction = (zero-shot six-fold mean - fine-tuned six-fold mean) / zero-shot six-fold mean (same convention as exp3_report.md §7).',
         'Data source: `result/models/exp3/stratified.csv` (generated by `code/49_exp3_summary.py`).'])


# ---------------------------------------------------------------- 2 source-domain forgetting table
def forgetting():
    F = [r for r in rcsv('result/models/exp3/source_forgetting.csv') if r['mask'] == 'active' and r['source_event'] == 'all_source']
    zero = {f: float(next(r['rmse'] for r in F if r['fold'] == f and r['method'] == 'zero')) for f in EVENTS}
    rows, lines = [], []
    z6 = np.mean(list(zero.values()))
    rows.append(dict(N=0, B_rmse=round(z6, 4), B_change_pct='', B_max_fold_change_pct='', Bp_rmse=round(z6, 4), Bp_change_pct='', Bp_max_fold_change_pct=''))
    lines.append(['0 (before fine-tuning, i.e. Exp. 2)', '%.4f' % z6, '—', '—', '%.4f' % z6, '—', '—'])
    for n in NS:
        rec = dict(N=n); ln = [str(n)]
        for m in ('B', 'Bp'):
            v = np.array([np.mean([float(r['rmse']) for r in F if r['fold'] == f and r['method'] == m and int(r['N']) == n]) for f in EVENTS])
            pct = 100 * (v - np.array([zero[f] for f in EVENTS])) / np.array([zero[f] for f in EVENTS])
            rec['%s_rmse' % m] = round(v.mean(), 4); rec['%s_change_pct' % m] = round(pct.mean(), 1); rec['%s_max_fold_change_pct' % m] = round(pct.max(), 1)
            ln += ['%.4f' % v.mean(), '%+.1f %%' % pct.mean(), '%+.1f %%' % pct.max()]
        rows.append(rec); lines.append(ln)
    wcsv('tab_e3_forget_v1', list(rows[0]), rows)
    wmd('tab_e3_forget_v1', 'Appendix table: Exp. 3 source-domain forgetting (single-step RMSE after fine-tuning on the 50 test runs of the other 5 events, active cells, six-fold mean)',
        ['N', 'B RMSE', 'B vs. before', 'B worst fold', "B′ RMSE", "B′ vs. before", "B′ worst fold"], lines,
        ['Source domain = the other 5 events used in training for that fold, 10 split_A test runs each, 50 runs pooled; before fine-tuning = the fold\'s Exp. 2 model (zero-shot) on the same runs.',
         'Each fold first averages the three seeds, then the six folds are averaged arithmetically; "vs. before" = (after - before) / before, computed per fold then averaged over six folds; "worst fold" is the maximum of that change over the six folds.',
         'Data source: `result/models/exp3/source_forgetting.csv` (generated by `code/49_exp3_summary.py`).'])


# ---------------------------------------------------------------- 3 event attribute table
def event_attrs():
    C = rcsv('result/models/exp3/correlates.csv')
    cur = [r for r in rcsv('result/models/exp3/curve_by_fold.csv') if r['mode'] == 'single' and r['mask'] == 'active']
    rows, lines = [], []
    for f in EVENTS:
        c = next(r for r in C if r['fold'] == f and r['method'] == 'B' and int(r['N']) == 5)
        b = next(r for r in cur if r['fold'] == f and r['method'] == 'B' and int(r['N']) == 5)
        rows.append(dict(event=EV_CN[f], exp1_rmse=round(float(b['exp1_rmse']), 4), zero_rmse=round(float(c['zero_rmse']), 4), B_N5_rmse=round(float(c['rmse']), 4),
                         B_N5_drop_pct=round(float(c['improvement_pct']), 1), exp2_degrade_ratio=float(c['degrade']),
                         wet_km2_testruns_mean=float(c['wet_km2']), rain_mm_81scen_mean=float(c['rain_mm']), rain_product=c['product']))
        lines.append([EV_CN[f], '%.4f' % float(b['exp1_rmse']), '%.4f' % float(c['zero_rmse']), '%.4f' % float(c['rmse']), '%.1f %%' % float(c['improvement_pct']),
                      '%.2f' % float(c['degrade']), '%.1f' % float(c['wet_km2']), '%.1f' % float(c['rain_mm']), c['product']])
    wcsv('tab_e3_attrs_v1', list(rows[0]), rows)
    wmd('tab_e3_attrs_v1', 'Appendix table: Exp. 3 per-event attributes and fine-tuning gain (single-step RMSE, active cells)',
        ['Event', 'Exp. 1', 'Zero-shot (Exp. 2)', 'B N=5', 'B N=5 reduction', 'Exp. 2 degradation factor', 'Wet area km^2', 'Total rainfall mm', 'Rainfall product'], lines,
        ['B N=5 is the mean of three seeds; reduction = (zero-shot - B N=5) / zero-shot; Exp. 2 degradation factor = zero-shot RMSE / Exp. 1 RMSE (consistent with the degrade column of `correlates.csv`).',
         'Wet area = mean SFINCS land inundation area (h > 0.1 m) over the event\'s 10 test runs; total rainfall = mean over the event\'s 81 scenarios (both from docs/PLAN.md §8 and exp2_report.md; the wet_km2 and rain_mm columns of `correlates.csv` are the same numbers registered in `code/49_exp3_summary.py`); the degradation factor is also taken from that file (2 decimals); rainfall product: MRMS or Stage IV.',
         'Data sources: `result/models/exp3/correlates.csv`, `result/models/exp3/curve_by_fold.csv`.'])


def main():
    os.makedirs(OUT, exist_ok=True)
    stratified(); forgetting(); event_attrs()
    for n in ('tab_e3_strat_v1', 'tab_e3_forget_v1', 'tab_e3_attrs_v1'):
        print('   final_report_materials/tables/%s.{csv,md}' % n)


if __name__ == '__main__':
    main()
