#!/usr/bin/env python3
"""62_setup_tables.py -- draft tables for the setup section of the final report (_v1, csv + tex). Writes only final_report_materials/tables/setup/.

Outputs:
  tab_events_v1.{csv,tex}        event table (after Sun et al. 2023 Table A1): hurricane / year / simulation start / main-period start / simulation end / rainfall product
  tab_unet_arch_v1.{csv,tex}     U-Net architecture table (after Sun et al. Table A2): layer / input channels / output channels / kernel -- read layer by layer from an instance of code/33
  tab_unet_hparams_v1.{csv,tex}  hyperparameter table, each item with its source file

Data sources (all read from files, nothing from memory):
  code/window_config.py                                   Irma window (T0 / spin-up / T1)
  data/static/meta/events_window10d_summary.json          windows of the other five events
  docs/DATA_SPEC.md §4 + data/<event>/raw/rain/ dir names  rainfall products
  code/33_modelB_unet.py                                  U-Net per-layer channels and kernels, total parameter count (counted from an instance)
  code/34_modelB_train.py, code/47_exp3_train.py          optimizer / learning rate / batch / epochs / early stopping / fine-tune settings (argparse defaults)
  docs/PLAN.md §1 §6.1 §6.5 §6.6 §7.5 §8.10 §8.17 §8.18   sampling, normalization, hardware, run time
  docs/PROGRESS.md                                        measured run time of Experiment 1

Usage: python3 code/62_setup_tables.py
"""
import os, sys, json, csv, datetime
import numpy as np
import torch

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'final_report_materials', 'tables', 'setup')
EVENTS = ['irma', 'matthew', 'ian', 'milton', 'dorian', 'beryl']
EV_CN = dict(irma='Irma', matthew='Matthew', ian='Ian', milton='Milton', dorian='Dorian', beryl='Beryl')
# rainfall products: read from directory names (Irma's raw cache is in raw/mrms_cache/; product name from docs/DATA_SPEC.md §4)
RAIN_PRODUCT = dict(irma='MRMS GaugeCorr_QPE_01H', matthew='MRMS GaugeCorr_QPE_01H',
                    ian='MRMS MultiSensor_QPE_01H_Pass2', milton='MRMS MultiSensor_QPE_01H_Pass2',
                    dorian='MRMS GaugeCorr_QPE_01H', beryl='Stage IV 01h')


def wcsv(name, cols, rows):
    with open(os.path.join(OUT, name + '.csv'), 'w', newline='') as f:
        w = csv.DictWriter(f, cols); w.writeheader(); w.writerows(rows)


def wtex(name, caption, header, rows, notes, align=None):
    align = align or ('l' * len(header))
    esc = lambda s: str(s).replace('_', r'\_').replace('%', r'\%').replace('&', r'\&')
    with open(os.path.join(OUT, name + '.tex'), 'w', encoding='utf-8') as f:
        f.write('%% %s -- draft, pending user verification; generated by code/62_setup_tables.py\n' % name)
        f.write('\\begin{table}[t]\n\\centering\n\\caption{%s}\n\\label{tab:%s}\n' % (esc(caption), name.replace('tab_', '').replace('_v1', '')))
        f.write('\\begin{tabular}{%s}\n\\toprule\n' % align)
        f.write(' & '.join(esc(h) for h in header) + ' \\\\\n\\midrule\n')
        for r in rows:
            f.write(' & '.join(esc(v) for v in r) + ' \\\\\n')
        f.write('\\bottomrule\n\\end{tabular}\n')
        if notes:
            f.write('\\\\[2pt]\n\\begin{minipage}{\\linewidth}\\footnotesize\n')
            for n in notes:
                f.write(esc(n) + '\\\\\n')
            f.write('\\end{minipage}\n')
        f.write('\\end{table}\n')


# ---------------------------------------------------------------- 1 event table
def events_table():
    import importlib.util
    spec = importlib.util.spec_from_file_location('wc', os.path.join(ROOT, 'code', 'window_config.py'))
    wc = importlib.util.module_from_spec(spec); spec.loader.exec_module(wc)
    summ = json.load(open(os.path.join(ROOT, 'data/static/meta/events_window10d_summary.json')))
    fmt = lambda s: str(s)[:16].replace('T', ' ')
    rec = {'irma': (wc.T0_ISO, wc.TSPIN_ISO, wc.T1_ISO)}
    for e in EVENTS:
        if e == 'irma':
            continue
        w = summ[e]['window']
        rec[e] = (fmt(w['T0']), fmt(w['spinup_end']), fmt(w['T1']))
    rows = []
    for e in EVENTS:
        t0, ts, t1 = rec[e]
        rows.append(dict(hurricane=EV_CN[e], year=int(t0[:4]), start_utc=t0, event_start_utc=ts,
                         end_utc=t1, rain_product=RAIN_PRODUCT[e]))
    rows.sort(key=lambda r: r['year'])
    wcsv('tab_events_v1', list(rows[0]), rows)
    wtex('tab_events_v1', 'Simulation windows and rainfall products of the six events (UTC)',
         ['Hurricane', 'Year', 'Simulation start UTC', 'Main-period start UTC', 'Simulation end UTC', 'Rainfall product'],
         [[r['hurricane'], r['year'], r['start_utc'], r['event_start_utc'], r['end_utc'], r['rain_product']] for r in rows],
         ['Each event is simulated for 10 days = 72 h spin-up + 168 h main period; main-period start = end of spin-up. '
          'Hourly label T represents the interval [T-1h, T), 240 labels in total; surrogate target times are t = 73…240 h.',
          'Each event has 81 compound-forcing scenarios (full combination of α, β, γ, τ); the baseline scenario is s041 (unperturbed); 486 SFINCS simulations across the six events.',
          'Experiment 2 (cross-event) is a 6-fold leave-one-out, with each event held out in turn, so there is no fixed Usage column.',
          'Sources: Irma from code/window\\_config.py; the other five events from data/static/meta/events\\_window10d\\_summary.json; '
          'rainfall products in docs/DATA\\_SPEC.md section 4.'],
         align='llllll')
    return rows


# ---------------------------------------------------------------- 2 U-Net architecture table
def unet_arch_table():
    import importlib.util
    spec = importlib.util.spec_from_file_location('u', os.path.join(ROOT, 'code', '33_modelB_unet.py'))
    U = importlib.util.module_from_spec(spec); spec.loader.exec_module(U)
    m = U.UNetV1()
    rows = []

    def conv_rows(block, tag):
        for i, layer in enumerate([l for l in block if isinstance(l, torch.nn.Conv2d)]):
            rows.append(dict(stage=tag, layer='Conv2d (%d/2)' % (i + 1), in_ch=layer.in_channels,
                             out_ch=layer.out_channels, kernel='%dx%d' % layer.kernel_size,
                             note='+ BatchNorm2d + ReLU'))

    for i, enc in enumerate(m.enc):
        conv_rows(enc, 'Encoder block E%d' % (i + 1))
        rows.append(dict(stage='Encoder block E%d' % (i + 1), layer='MaxPool2d', in_ch=m.enc[i][3].out_channels,
                         out_ch=m.enc[i][3].out_channels, kernel='2x2', note='stride 2, halves spatial size'))
    conv_rows(m.bottom, 'Bottleneck B')
    for i, (up, dec) in enumerate(zip(m.up, m.dec)):
        rows.append(dict(stage='Decoder block D%d' % (i + 1), layer='ConvTranspose2d', in_ch=up.in_channels,
                         out_ch=up.out_channels, kernel='%dx%d' % up.kernel_size, note='stride 2, doubles spatial size'))
        rows.append(dict(stage='Decoder block D%d' % (i + 1), layer='Concat (skip connection)', in_ch=up.out_channels,
                         out_ch=2 * up.out_channels, kernel='—', note='channel-wise concatenation with the same-level encoder output'))
        conv_rows(dec, 'Decoder block D%d' % (i + 1))
    head = [l for l in m.head if isinstance(l, torch.nn.Conv2d)][0]
    rows.append(dict(stage='Output head', layer='Conv2d', in_ch=head.in_channels, out_ch=head.out_channels,
                     kernel='%dx%d' % head.kernel_size, note='+ ReLU, ensures h >= 0'))
    npar = U.n_params(m)
    with torch.no_grad():
        oshape = tuple(m(torch.zeros(1, 13, 208, 256)).shape)
    wcsv('tab_unet_arch_v1', list(rows[0]), rows)
    wtex('tab_unet_arch_v1', 'Layer-by-layer structure of U-Net v1 (input $13\\times208\\times256$, output $%d\\times%d$)' % (oshape[1], oshape[2]),
         ['Stage', 'Layer', 'In channels', 'Out channels', 'Kernel', 'Note'],
         [[r['stage'], r['layer'], r['in_ch'], r['out_ch'], r['kernel'], r['note']] for r in rows],
         ['Input channels C = 13: bed elevation zb 1 + depth look-back h(t-1), h(t-2), h(t-3) 3 + '
          'rainfall look-back 3 (ampr blocks t-1, t-2, t-3) + seaward water level 3 + river discharge 3.',
          'Water level and discharge are scalars; each takes 1 channel by "tiling the scalar value at that time over the whole map" (i.e. a constant map); '
          'padded rows/columns get 0 for that value. The original 195x255 grid is padded to 208x256 in the training code (13 rows on the north side, 1 column on the east side, divisible by 16), '
          'and the output is cropped back to 195x255 to compute the loss; padded and inactive cells are excluded from the loss.',
          'Each encoder / decoder block is 2 x (3x3 convolution + BatchNorm + ReLU); downsampling uses 2x2 max pooling, upsampling uses 2x2 transposed convolution, '
          'skip connections are channel-wise concatenation. Encoder channels 32→64→128→256, bottleneck 512, 4 downsampling steps.',
          '**Counted total number of parameters: %s** (sum over model.parameters() in torch; source code/33\\_modelB\\_unet.py).' % f'{npar:,}'],
         align='llrrll')
    return npar, oshape


# ---------------------------------------------------------------- 3 hyperparameter table
def hparams_table(npar):
    S34, S47 = 'code/34_modelB_train.py', 'code/47_exp3_train.py'
    P = 'docs/PLAN.md'
    rows = [
        ('Model', 'U-Net v1; 4 downsampling steps, encoder 32/64/128/256, bottleneck 512; %s parameters' % f'{npar:,}', 'code/33_modelB_unet.py'),
        ('Input / output', 'input 13 x 208 x 256 (after padding); output h(t) of 195 x 255', 'code/32_modelB_data.py, code/33'),
        ('Optimizer', 'Adam (default betas)', '%s (torch.optim.Adam)' % S34),
        ('Learning rate and schedule', '1e-3, fixed throughout, **no schedule**', '%s --lr default; %s §6.1' % (S34, P)),
        ('Loss function', 'masked MSE on active cells; padded and inactive cells excluded', '%s masked_mse(); %s §6.1' % (S34, P)),
        ('batch size', '8', '%s --batch-size; %s §6.1' % (S34, P)),
        ('Max epochs', '50', '%s --epochs default; %s §6.1' % (S34, P)),
        ('Early stopping', 'stop when validation loss does not decrease for 10 consecutive epochs (patience = 10); best epoch selected by validation loss', '%s --patience default; %s §6.1' % (S34, P)),
        ('Train / val sampling', 'each run uses fixed t = 73, 80, 87, …, 234 (one every 7 h, 24 times); run and sample order shuffled every epoch, the t set is unchanged',
         '%s --t-list 73:234:7; %s §6.1 §6.5' % (S34, P)),
        ('Test sampling', 'all 168 times (t = 73…240), no subsampling', '%s §6.1' % P),
        ('Normalization', 'per-channel z-score; statistics computed **only on the respective training set** (zb on active cells, h and rainfall on active cells and frames 70…239, one set each for water level and discharge); '
         'target h(t) not normalized (unit m); Experiment 3 reuses the norm_stats of the same Experiment 2 fold',
         'code/32_modelB_data.py (Normalizer); %s §6.1 §8.2' % P),
        ('Random seed', '42 (Experiments 1 / 2); Experiment 3 additionally uses seeds 0 / 1 / 2 for sampling, sample order and initialization of C', '%s; %s §6.1 §8.10' % (S34, P)),
        ('Hardware (Experiment 1)', 'Apple M4, MPS backend (16 GB unified memory)', '%s §6.6; docs/PROGRESS.md' % P),
        ('Hardware (Experiments 2 / 3)', 'Google Colab, NVIDIA A100', '%s §7.5 §8.20' % P),
        ('Time per epoch (Experiment 1, MPS)', 'epoch 1 562.8 s (training 527.9 s + validation 34.8 s), about 0.45–0.49 s/step; 42 epochs 6.10 h in total',
         '%s §6.6; docs/PROGRESS.md' % P),
        ('Time per epoch (Experiment 2, A100)', 'about 0.121 s/step, 900 steps/epoch ≈ 109 s; 50 epochs 1.69 h per fold', '%s §7.5' % P),
        ('Inference time per time step', 'about 4.2 ms per time step (A100; measured single-step evaluation of 10 runs x 168 times takes about 7 s)', '%s §8.18' % P),
        ('Experiment 3 B (full fine-tune)', 'learning rate 1e-4; fixed 20 epochs; no early stopping, no validation set; start = model_best of the same Experiment 2 fold',
         '%s --lr/--epochs defaults; %s §8.10 §8.17' % (S47, P)),
        ("Experiment 3 B' (frozen encoder)", 'learning rate 1e-4; fixed 20 epochs; encoder blocks and bottleneck frozen, only decoder blocks and output head trained',
         '%s build_model(); %s §8.10 §8.17' % (S47, P)),
        ('Experiment 3 C (from scratch)', 'learning rate 1e-3; fixed 50 epochs; random initialization, only the N runs',
         '%s --lr/--epochs defaults; %s §8.10 §8.17' % (S47, P)),
    ]
    out = [dict(item=a, setting=b, source=c) for a, b, c in rows]
    wcsv('tab_unet_hparams_v1', ['item', 'setting', 'source'], out)
    wtex('tab_unet_hparams_v1', 'Training settings and hyperparameters of U-Net v1 (source file noted for each item)',
         ['Item', 'Setting', 'Source'], [[a, b, c] for a, b, c in rows],
         ['The different learning rates of B and C are intentional: B starts from converged pretrained weights and needs small steps; C starts from random initialization and needs a step size of the same order as pretraining. '
          'Both use a fixed number of epochs without early stopping, so that C does not gain extra exposure to target-event data through a validation set (see docs/PLAN.md §8.10 item 4).',
          '"Inference time per time step" is derived from the measured evaluation time: 7 s / (10 runs x 168 times) ≈ 4.2 ms.'],
         align='llp{0.34\\linewidth}')
    return out


def main():
    os.makedirs(OUT, exist_ok=True)
    ev = events_table()
    npar, oshape = unet_arch_table()
    hp = hparams_table(npar)
    for n in ('tab_events_v1', 'tab_unet_arch_v1', 'tab_unet_hparams_v1'):
        print('   final_report_materials/tables/setup/%s.{csv,tex}' % n)
    print('events %d rows; U-Net parameters %s; output shape %s; hyperparameters %d rows' % (len(ev), f'{npar:,}', oshape, len(hp)))


if __name__ == '__main__':
    main()
