#!/usr/bin/env python3
"""66_setup_tables_v2.py -- setup tables, round 2 (condensed versions + new scenario table). Writes only final_report_materials/tables/setup/.

Standalone script: does not touch code/62 or its _v1 outputs.

Outputs:
  tab_unet_arch_v2.{csv,tex}     condensed architecture table, compact format after Sun et al. 2023 Table A2: layer / in channels / out channels / kernel.
                                 Symmetric encoder-decoder layers merged (the 2 convs of each block on one row, pooling / upsampling on the same row), 11 rows, fits one page.
                                 Table note keeps a single sentence: the composition of input channels C.
  tab_unet_hparams_v2.{csv,tex}  condensed hyper-parameter table; the report .tex keeps only 12 items + 1 merged Exp-3 row, a short phrase per row, no full sentences;
                                 **source annotations only in the .csv**, not in the .tex.
  tab_scenarios_v1.{csv,tex}     hurricane-variant table (new): how one hurricane yields 81 variants. Columns = factor / symbol / values / applied to.

Data sources (all actually read):
  code/33_modelB_unet.py                 channel counts, kernels, parameter count of the architecture table (read layer by layer after instantiation)
  code/22_make_scenarios.py              ALPHAS / BETAS / GAMMAS / TAUS, the (alpha,beta,gamma,tau)->ID enumeration order, the three application formulas
  data/irma/scenarios/manifest.csv       check of the baseline scenario ID (is_baseline)
  code/34_modelB_train.py, code/47_exp3_train.py, docs/PLAN.md   hyper-parameters
  measured output of code/64_infer_timing.py     inference time per time step

Usage: python3 code/66_setup_tables_v2.py
"""
import os, csv, importlib.util, itertools
import torch

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'final_report_materials', 'tables', 'setup')


def wcsv(name, cols, rows):
    with open(os.path.join(OUT, name + '.csv'), 'w', newline='') as f:
        w = csv.DictWriter(f, cols); w.writeheader(); w.writerows(rows)


def wtex(name, caption, header, rows, notes, align=None):
    align = align or ('l' * len(header))
    esc = lambda s: str(s).replace('_', r'\_').replace('%', r'\%').replace('&', r'\&')
    with open(os.path.join(OUT, name + '.tex'), 'w', encoding='utf-8') as f:
        f.write('%% %s -- draft, pending user review; generated by code/66_setup_tables_v2.py\n' % name)
        f.write('\\begin{table}[t]\n\\centering\n\\caption{%s}\n\\label{tab:%s}\n' % (esc(caption), name.replace('tab_', '').replace('_v', '')))
        f.write('\\begin{tabular}{%s}\n\\toprule\n' % align)
        f.write(' & '.join(esc(h) for h in header) + ' \\\\\n\\midrule\n')
        for r in rows:
            f.write(' & '.join(esc(v) for v in r) + ' \\\\\n')
        f.write('\\bottomrule\n\\end{tabular}\n')
        if notes:
            f.write('\\\\[2pt]\n\\begin{minipage}{\\linewidth}\\footnotesize\n')
            for n in notes:
                f.write(esc(n) + '\\\\\n')
            f.write('\\end{minipage}\n')
        f.write('\\end{table}\n')


def unet():
    spec = importlib.util.spec_from_file_location('u', os.path.join(ROOT, 'code', '33_modelB_unet.py'))
    U = importlib.util.module_from_spec(spec); spec.loader.exec_module(U)
    return U, U.UNetV1()


# ---------------------------------------------------------------- 1 architecture table (condensed)
def arch_v2():
    U, m = unet()
    W = [e[0].out_channels for e in m.enc]                 # 32, 64, 128, 256 (read from the model)
    cin = m.enc[0][0].in_channels                          # 13
    bot = m.bottom[0].out_channels                         # 512
    head = [l for l in m.head if isinstance(l, torch.nn.Conv2d)][0]
    rows = [dict(layer='Input', in_ch='—', out_ch=cin, kernel='—')]
    prev = cin
    for i, w in enumerate(W):
        rows.append(dict(layer='Encoder block %d (2 conv) + max pool' % (i + 1), in_ch=prev, out_ch=w, kernel='3x3 / 2x2'))
        prev = w
    rows.append(dict(layer='Bottleneck (2 conv)', in_ch=prev, out_ch=bot, kernel='3x3'))
    prev = bot
    for i, w in enumerate(reversed(W)):
        k = len(W) - i
        rows.append(dict(layer='Up-conv %d + skip concat + Decoder block %d (2 conv)' % (k, k),
                         in_ch=prev, out_ch=w, kernel='2x2 / 3x3'))
        prev = w
    rows.append(dict(layer='Output conv', in_ch=prev, out_ch=head.out_channels, kernel='1x1'))
    npar = U.n_params(m)
    wcsv('tab_unet_arch_v2', ['layer', 'in_ch', 'out_ch', 'kernel'], rows)
    wtex('tab_unet_arch_v2', 'U-Net v1 architecture (%s parameters)' % f'{npar:,}',
         ['Layer', 'In ch.', 'Out ch.', 'Kernel'],
         [[r['layer'], r['in_ch'], r['out_ch'], r['kernel']] for r in rows],
         ['Input channels C = %d: bed elevation 1 + depth look-back 3 + rainfall look-back 3 + seaward water level 3 + river discharge 3; '
          'water level and discharge are scalars, each broadcast to a constant map at its time step.' % cin],
         align='lrrl')
    return npar, cin


# ---------------------------------------------------------------- 2 hyper-parameter table (condensed)
def hparams_v2(npar):
    S34, S47, P = 'code/34_modelB_train.py', 'code/47_exp3_train.py', 'docs/PLAN.md'
    rows = [
        ('Optimizer', 'Adam', S34),
        ('Learning rate', '1e-3', '%s; %s §6.1' % (S34, P)),
        ('LR schedule', 'None; fixed throughout', '%s; %s §6.1' % (S34, P)),
        ('Loss', 'MSE masked to active cells', '%s masked_mse()' % S34),
        ('batch size', '8', '%s; %s §6.1' % (S34, P)),
        ('Max epochs', '50', '%s; %s §6.1' % (S34, P)),
        ('Early stopping', 'Validation loss flat for 10 epochs', '%s --patience; %s §6.1' % (S34, P)),
        ('Training sampling', 'One time step every 7 h; 24 per run', '%s --t-list 73:234:7; %s §6.1 §6.5' % (S34, P)),
        ('Input normalization', 'Training-set z-score, per channel group', 'code/32_modelB_data.py; %s §6.1' % P),
        ('Parameters', f'{npar:,}', 'code/33_modelB_unet.py'),
        ('Hardware', 'Exp-1 Apple M4 (MPS); Exp-2 / 3 NVIDIA A100', '%s §6.6 §7.5 §8.20' % P),
        ('Inference time per time step', '11.4 ms (measured on the local Mac MPS; about 4.2 ms scaled to the A100)',
         'measured by code/64_infer_timing.py; A100 value scaled per %s §8.18' % P),
        ("Exp-3 B / B' / C", 'LR 1e-4 / 1e-4 / 1e-3; epochs 20 / 20 / 50',
         '%s --lr/--epochs; %s §8.10 §8.17' % (S47, P)),
    ]
    wcsv('tab_unet_hparams_v2', ['item', 'setting', 'source'],
         [dict(item=a, setting=b, source=c) for a, b, c in rows])
    wtex('tab_unet_hparams_v2', 'U-Net v1 training setup and hyper-parameters',
         ['Item', 'Setting'], [[a, b] for a, b, _ in rows], [], align='ll')   # .tex has no source column
    return rows


# ---------------------------------------------------------------- 3 hurricane-variant table (new)
def scenarios_v1():
    spec = importlib.util.spec_from_file_location('mk', os.path.join(ROOT, 'code', '22_make_scenarios.py'))
    # that script really generates scenarios and must not be exec-ed; parse the constant line from its source instead (read-only)
    src = open(os.path.join(ROOT, 'code', '22_make_scenarios.py'), encoding='utf-8').read()
    line = next(l for l in src.split('\n') if l.startswith('ALPHAS, BETAS, GAMMAS, TAUS'))
    ALPHAS, BETAS, GAMMAS, TAUS = eval(line.split('=', 1)[1].strip())
    order = list(itertools.product(ALPHAS, BETAS, GAMMAS, TAUS))
    base_i = order.index((1.0, 1.0, 1.0, 0)) + 1
    # cross-check against is_baseline in the manifest
    import csv as _csv
    man = list(_csv.DictReader(open(os.path.join(ROOT, 'data/irma/scenarios/manifest.csv'))))
    base_sid = next(r['scenario'] for r in man if r['is_baseline'] in ('True', 'true'))
    assert base_sid.endswith('s%03d' % base_i), (base_sid, base_i)
    assert len(man) == len(order) == 81, (len(man), len(order))

    fmt = lambda v: ' / '.join((('%+d' % x) if x else '0') if isinstance(x, int) else ('%g' % x) for x in v)
    rows = [
        dict(factor='Non-tidal residual scale', symbol='α', values=fmt(ALPHAS),
             target='Non-tidal residual of the Mayport 8720218 water level: h_s = h_tide + α (h_obs − h_tide)'),
        dict(factor='Rainfall scale', symbol='β', values=fmt(BETAS),
             target='Per-cell rainfall intensity over the whole domain: P_s(x, t) = β P(x, t − τ)'),
        dict(factor='Low-frequency discharge scale', symbol='γ', values=fmt(GAMMAS),
             target='Low-frequency component of the Acosta 02246500 discharge: Q_s = γ Q_low + (Q − Q_low), Q_low = 25 h centered moving average'),
        dict(factor='Rainfall time shift (h)', symbol='τ', values=fmt(TAUS),
             target='Whole rainfall field shifted in time: P_s(x, t) = β P(x, t − τ)'),
    ]
    wcsv('tab_scenarios_v1', ['factor', 'symbol', 'values', 'target'], rows)
    wtex('tab_scenarios_v1', 'Compound-forcing scenarios of one hurricane: four factors with three levels each, %d variants in total' % len(order),
         ['Factor', 'Symbol', 'Values', 'Applied to'],
         [[r['factor'], r['symbol'], r['values'], r['target']] for r in rows],
         ['3 x 3 x 3 x 3 = %d scenarios; α = β = γ = 1 and τ = 0 is the unperturbed original forcing, ID \\textbf{s%03d} (checked against is_baseline in the manifest).'
          % (len(order), base_i),
          'IDs enumerate (α, β, γ, τ) in lexicographic order (τ varies fastest, α slowest): s001 = (%g, %g, %g, %+d), s081 = (%g, %g, %g, %+d).'
          % (*order[0], *order[-1]),
          'Each of the six events gets the same set of %d scenarios, %d SFINCS simulations in total.' % (len(order), 6 * len(order))],
         align='llp{0.16\\linewidth}p{0.42\\linewidth}')
    return base_i, base_sid, len(order)


def main():
    os.makedirs(OUT, exist_ok=True)
    npar, cin = arch_v2()
    hp = hparams_v2(npar)
    bi, bsid, n = scenarios_v1()
    for t in ('tab_unet_arch_v2', 'tab_unet_hparams_v2', 'tab_scenarios_v1'):
        print('   final_report_materials/tables/setup/%s.{csv,tex}' % t)
    print('architecture table: input channels %d, parameters %s; hyper-parameter table %d rows; scenario table %d scenarios, baseline = %s (index %d)'
          % (cin, f'{npar:,}', len(hp), n, bsid, bi))


if __name__ == '__main__':
    main()
