#!/usr/bin/env python3
"""68_setup_hparams_v3.py -- hyperparameter table v3 (sectioned version). Writes only final_report_materials/tables/setup/tab_unet_hparams_v3.{csv,tex}.

Standalone script: does not touch code/62, code/66 or their _v1 / _v2 outputs.

Changes relative to v2 (round-4 review comments, 2026-09-20):
  - The table body is split into two sections separated by \\midrule, each with a section title row (written only in the "Item" column, "Setting" column left empty):
      upper section "Pre-training": optimizer / learning rate / LR schedule / loss / batch size / max epochs / early stopping / training sampling interval / input normalization
      lower section "Fine-tuning (Exp. 3)": learning rate and epochs of B / B' / C (one row)
  - The three rows "Parameters / Hardware / Inference time per time step" belong to no section and are placed before both sections
  - Row text no longer repeats the section name (the fine-tuning row changed from "Exp. 3 B / B' / C" to "B / B' / C")
  - The .csv gains a column `section` (value empty / pre-training / fine-tuning); the source column is kept; section titles are not in the csv (expressed by the section column)

Data sources: code/33_modelB_unet.py (parameter count, counted after instantiation), argparse defaults of code/34_modelB_train.py and code/47_exp3_train.py,
          docs/PLAN.md §6.1 §6.5 §6.6 §7.5 §8.10 §8.17 §8.18, local measurement by code/64_infer_timing.py.

Usage: python3 code/68_setup_hparams_v3.py
"""
import os, csv, importlib.util

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'final_report_materials', 'tables', 'setup')
S34, S47, P = 'code/34_modelB_train.py', 'code/47_exp3_train.py', 'docs/PLAN.md'


def n_params():
    spec = importlib.util.spec_from_file_location('u', os.path.join(ROOT, 'code', '33_modelB_unet.py'))
    U = importlib.util.module_from_spec(spec); spec.loader.exec_module(U)
    return U.n_params(U.UNetV1())


def build(npar):
    """Return [(section, item, setting, source)]; section is '' / pre-training / fine-tuning (kept as Chinese literal values, read by code/71 and code/72)."""
    return [
        ('', 'Parameters', f'{npar:,}', 'code/33_modelB_unet.py'),
        ('', 'Hardware', 'Exp. 1 Apple M4 (MPS); Exp. 2 / 3 NVIDIA A100', '%s §6.6 §7.5 §8.20' % P),
        ('', 'Inference time per time step', '11.4 ms (measured on local Mac MPS; ~4.2 ms scaled to A100)',
         'code/64_infer_timing.py measurement; A100 value scaled per %s §8.18' % P),
        ('Pre-training', 'Optimizer', 'Adam', S34),
        ('Pre-training', 'Learning rate', '1e-3', '%s; %s §6.1' % (S34, P)),
        ('Pre-training', 'LR schedule', 'None, fixed throughout', '%s; %s §6.1' % (S34, P)),
        ('Pre-training', 'Loss', 'MSE masked to active cells', '%s masked_mse()' % S34),
        ('Pre-training', 'batch size', '8', '%s; %s §6.1' % (S34, P)),
        ('Pre-training', 'Max epochs', '50', '%s; %s §6.1' % (S34, P)),
        ('Pre-training', 'Early stopping', 'Validation loss not improving for 10 epochs', '%s --patience; %s §6.1' % (S34, P)),
        ('Pre-training', 'Training sampling interval', 'One time step every 7 h, 24 per run', '%s --t-list 73:234:7; %s §6.1 §6.5' % (S34, P)),
        ('Pre-training', 'Input normalization', 'Training-set z-score, per channel group', 'code/32_modelB_data.py; %s §6.1' % P),
        ('Fine-tuning', "B / B' / C", 'Learning rate 1e-4 / 1e-4 / 1e-3; epochs 20 / 20 / 50',
         '%s --lr/--epochs; %s §8.10 §8.17' % (S47, P)),
    ]


SECTION_TITLE = {'Pre-training': 'Pre-training', 'Fine-tuning': 'Fine-tuning (Exp. 3)'}


def write(rows, name='tab_unet_hparams_v3'):
    with open(os.path.join(OUT, name + '.csv'), 'w', newline='') as f:
        w = csv.DictWriter(f, ['item', 'setting', 'source', 'section']); w.writeheader()
        for sec, it, st, src in rows:
            w.writerow(dict(item=it, setting=st, source=src, section=sec))

    esc = lambda s: str(s).replace('_', r'\_').replace('%', r'\%').replace('&', r'\&')
    with open(os.path.join(OUT, name + '.tex'), 'w', encoding='utf-8') as f:
        f.write('%% %s -- draft, pending user review; generated by code/68_setup_hparams_v3.py\n' % name)
        f.write('\\begin{table}[t]\n\\centering\n\\caption{Training settings and hyperparameters of U-Net v1}\n\\label{tab:unet-hparams}\n')
        f.write('\\begin{tabular}{ll}\n\\toprule\nItem & Setting \\\\\n\\midrule\n')
        prev = None
        for sec, it, st, _src in rows:
            if sec != prev:
                if prev is not None:
                    f.write('\\midrule\n')
                if sec:
                    f.write('\\textit{%s} & \\\\\n' % esc(SECTION_TITLE[sec]))   # section title: only in the "Item" column
                prev = sec
            f.write('%s & %s \\\\\n' % (esc(it), esc(st)))
        f.write('\\bottomrule\n\\end{tabular}\n\\end{table}\n')


def main():
    os.makedirs(OUT, exist_ok=True)
    rows = build(n_params())
    write(rows)
    print('   final_report_materials/tables/setup/tab_unet_hparams_v3.{csv,tex}')
    print('%d data rows in total (no section %d / pre-training %d / fine-tuning %d) + 2 section title rows (only in .tex)'
          % (len(rows), sum(1 for r in rows if not r[0]),
             sum(1 for r in rows if r[0] == 'Pre-training'), sum(1 for r in rows if r[0] == 'Fine-tuning')))


if __name__ == '__main__':
    main()
