#!/usr/bin/env python3
"""70_latex_tables_zh.py -- generate / collect table .tex files for the Overleaf Chinese package. Writes only final_report_materials/draft/latex_zh/tables/.

Two tasks:
  1. The six experiment tables (tab_e12_main, tab_e1_full, tab_e2_full, tab_e3_strat / forget / attrs) previously existed only as csv + md;
     generate .tex (booktabs) with caption / label from the csv. The original csv / md are not touched.
  2. The four setup tables already have .tex; copy them over. The **copies** get two minimal changes: (1) wide tables table -> table*; (2) Unicode symbols
     missing from the Times (Type1) font (>= minus x -> ~ +- <= prime ^2 ^3 alpha beta gamma tau ellipsis em-dash en-dash) are replaced by LaTeX math / text commands, otherwise XeLaTeX shows boxes or errors.
     The original final_report_materials/tables/setup/*.tex are not touched.

Label convention (all ASCII): tab:e12-main, tab:e1-full, tab:e2-full, tab:e3-strat, tab:e3-forget, tab:e3-attrs;
setup tables keep their original labels: tab:events, tab:scenarios1, tab:unet-hparams, tab:unet_arch2.

Usage: python3 code/70_latex_tables_zh.py
"""
import os, csv, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'final_report_materials', 'tables')
OUT = os.path.join(ROOT, 'final_report_materials', 'draft', 'latex_zh', 'tables')

# Characters missing from Times Type1 -> LaTeX. Order matters (longer first).
UNI = [('≥', r'$\geq$'), ('≤', r'$\leq$'), ('≈', r'$\approx$'), ('×', r'$\times$'), ('→', r'$\to$'), ('±', r'$\pm$'),
       ('−', r'$-$'), ('′', r'$^{\prime}$'), ('²', r'$^{2}$'), ('³', r'$^{3}$'), ('α', r'$\alpha$'), ('β', r'$\beta$'),
       ('γ', r'$\gamma$'), ('τ', r'$\tau$'), ('…', r'\ldots{}'), ('—', '---'), ('–', '--'), ('₀', r'$_{0}$')]


def sane(t):
    for a, b in UNI:
        t = t.replace(a, b)
    return t


def esc(t):
    """csv cell -> LaTeX: first escape % _ & #, then replace Unicode symbols."""
    t = str(t).replace('%', r'\%').replace('_', r'\_').replace('&', r'\&').replace('#', r'\#')
    return sane(t)


def write_tex(name, caption, label, header, rows, notes, align, star=True, size=r'\small'):
    env = 'table*' if star else 'table'
    with open(os.path.join(OUT, name + '.tex'), 'w', encoding='utf-8') as f:
        f.write('%% %s -- generated by code/70_latex_tables_zh.py from final_report_materials/tables/%s.csv; draft, pending review\n' % (name, name))
        f.write('\\begin{%s}[t]\n\\centering\n%s\n\\caption{%s}\n\\label{%s}\n' % (env, size, sane(caption), label))
        f.write('\\begin{tabular}{%s}\n\\toprule\n' % align)
        f.write(' & '.join(esc(h) for h in header) + ' \\\\\n\\midrule\n')
        for r in rows:
            bold = r.get('_bold', False)
            cells = [esc(v) for v in r['_cells']]
            if bold:
                cells = ['\\textbf{%s}' % c for c in cells]
            f.write(' & '.join(cells) + ' \\\\\n')
        f.write('\\bottomrule\n\\end{tabular}\n')
        if notes:
            f.write('\\\\[3pt]\n\\begin{minipage}{\\linewidth}\\footnotesize\n')
            for n in notes:
                f.write(esc(n) + '\\\\\n')
            f.write('\\end{minipage}\n')
        f.write('\\end{%s}\n' % env)


def rcsv(name):
    return list(csv.DictReader(open(os.path.join(SRC, name + '.csv'), encoding='utf-8')))


# ---------------------------------------------------------------- 1 Exp. 1 / 2 full tables (appendix)
def full_table(name, caption, label):
    rows = rcsv(name)
    out = []
    for r in rows:
        out.append(dict(_cells=[r['event'], r['mode'], '%.4f' % float(r['mae_active']), '%.4f' % float(r['rmse_active']),
                                '%.3f' % float(r['csi01_active']), '%.3f' % float(r['csi03_active']),
                                '%.4f' % float(r['mae_land']), '%.4f' % float(r['rmse_land']),
                                '%.3f' % float(r['csi01_land']), '%.3f' % float(r['csi03_land'])],
                        _bold=(r['event'] == 'All')))
    write_tex(name, caption, label,
              ['Event', 'Prediction mode', 'MAE active', 'RMSE active', 'CSI 0.1 active', 'CSI 0.3 active', 'MAE land', 'RMSE land', 'CSI 0.1 land', 'CSI 0.3 land'],
              out,
              ['MAE / RMSE in m; CSI dimensionless, wet = h > threshold, CSI = TP / (TP + FP + FN). 24,467 active cells, 21,933 land cells (active and zb ≥ 0); '
               'each event row pools that event\'s 10 test runs × 168 time steps × cells; the total row pools 60 runs. Persistence = the SFINCS truth at t−1 used as the prediction at t.'],
              'llrrrrrrrr', star=True, size=r'\footnotesize')


# ---------------------------------------------------------------- 2 main-text combined table
def main_table():
    rows = rcsv('tab_e12_main_v1'); out = []
    for r in rows:
        out.append(dict(_cells=[r['event'], '%.4f' % float(r['single_rmse_exp1']), '%.4f' % float(r['single_rmse_exp2']),
                                '%.4f' % float(r['persistence_rmse']), '%.4f' % float(r['rollout_rmse_exp1']),
                                '%.4f' % float(r['rollout_rmse_exp2']), '%.3f' % float(r['single_csi01_exp1']),
                                '%.3f' % float(r['single_csi01_exp2'])], _bold=(r['event'] == 'All')))
    write_tex('tab_e12_main_v1', 'Main metrics of Exp. 1 (same event) and Exp. 2 (cross-event, 6-fold leave-one-out): single-step / rollout RMSE and the Persistence baseline (active cells, m), single-step CSI (threshold 0.1 m)',
              'tab:e12-main',
              ['Event', 'Single-step RMSE Exp. 1', 'Single-step RMSE Exp. 2', 'Persistence RMSE', 'Rollout RMSE Exp. 1', 'Rollout RMSE Exp. 2', 'Single-step CSI 0.1 Exp. 1', 'Single-step CSI 0.1 Exp. 2'],
              out,
              ['Each Exp. 2 row is the result with that event held out (the event was never seen in training); the test set is the same as in Exp. 1 (the event\'s 10 test runs, all 168 time steps). '
               'Persistence is model-independent and shared by both experiments. Each row pools 10 runs × 168 time steps × active cells; the total row pools 60 runs. '
               'Full metrics (incl. land cells, MAE, CSI 0.3) are in the appendix table.'],
              'lrrrrrrr', star=True)


# ---------------------------------------------------------------- 3 three Exp. 3 appendix tables
def e3_tables():
    rows = rcsv('tab_e3_strat_v1')
    write_tex('tab_e3_strat_v1', 'Exp. 3 stratified results: single-step RMSE from zero-shot → B fine-tuning (active cells, six-fold mean) and reduction', 'tab:e3-strat',
              ['Stratum', 'Zero-shot', 'B N=5', 'Reduction', 'B N=10', 'Reduction'],
              [dict(_cells=[r['stratum'], '%.4f' % float(r['zero_rmse']), '%.4f' % float(r['B_N5_rmse']), '%.1f %%' % float(r['B_N5_drop_pct']),
                            '%.4f' % float(r['B_N10_rmse']), '%.1f %%' % float(r['B_N10_drop_pct'])]) for r in rows],
              ['The compound forcing level is defined by (α, β, γ) (low / medium / high, 27 scenarios each); the rainfall time shift τ is −6 / 0 / +6 h (27 scenarios each). Each fold first pools the three seeds; "six-fold mean" is the arithmetic mean of the six fold RMSEs; '
               'reduction = (zero-shot six-fold mean − fine-tuned six-fold mean) / zero-shot six-fold mean.'],
              'lrrrrr', star=False)

    rows = rcsv('tab_e3_forget_v1'); out = []
    for r in rows:
        n = r['N']
        f = lambda k, fmt: (fmt % float(r[k])) if r[k] not in ('', None) else '---'
        out.append(dict(_cells=[('0 (before fine-tuning)' if n == '0' else n), f('B_rmse', '%.4f'), f('B_change_pct', '%+.1f %%'), f('B_max_fold_change_pct', '%+.1f %%'),
                                f('Bp_rmse', '%.4f'), f('Bp_change_pct', '%+.1f %%'), f('Bp_max_fold_change_pct', '%+.1f %%')]))
    write_tex('tab_e3_forget_v1', 'Exp. 3 source-domain forgetting: single-step RMSE after fine-tuning on the 50 test runs of the other 5 events (active cells, six-fold mean) and change relative to before fine-tuning', 'tab:e3-forget',
              ['N', 'B RMSE', 'B vs. before', 'B worst fold', 'B′ RMSE', 'B′ vs. before', 'B′ worst fold'], out,
              ['Source domain = the other 5 events used in training for that fold, 10 test runs each, 50 runs pooled; before fine-tuning = the fold\'s Exp. 2 model (zero-shot) on the same runs. '
               'Each fold first averages the three seeds, then the six folds are averaged arithmetically; "vs. before" = (after − before) / before, computed per fold then averaged over six folds; "worst fold" is the maximum of that change over the six folds.'],
              'lrrrrrr', star=True)

    rows = rcsv('tab_e3_attrs_v1')
    write_tex('tab_e3_attrs_v1', 'Exp. 3 per-event attributes and fine-tuning gain (single-step RMSE, active cells)', 'tab:e3-attrs',
              ['Event', 'Exp. 1', 'Zero-shot', 'B N=5', 'B N=5 reduction', 'Exp. 2 degradation factor', 'Wet area km²', 'Total rainfall mm', 'Rainfall product'],
              [dict(_cells=[r['event'], '%.4f' % float(r['exp1_rmse']), '%.4f' % float(r['zero_rmse']), '%.4f' % float(r['B_N5_rmse']),
                            '%.1f %%' % float(r['B_N5_drop_pct']), '%.2f' % float(r['exp2_degrade_ratio']),
                            '%.1f' % float(r['wet_km2_testruns_mean']), '%.1f' % float(r['rain_mm_81scen_mean']), r['rain_product']]) for r in rows],
              ['B N=5 is the mean of three seeds; reduction = (zero-shot − B N=5) / zero-shot; Exp. 2 degradation factor = zero-shot RMSE / Exp. 1 RMSE. '
               'Wet area = mean SFINCS land inundation area (h > 0.1 m) over the event\'s 10 test runs; total rainfall = mean over the event\'s 81 scenarios; rainfall product: MRMS or Stage IV.'],
              'lrrrrrrrl', star=True)


# ---------------------------------------------------------------- 4 setup tables: copy and apply minimal changes
def setup_tables():
    star = {'tab_events_v1': True, 'tab_scenarios_v1': True, 'tab_unet_hparams_v3': False, 'tab_unet_arch_v2': True}
    for name, st in star.items():
        s = open(os.path.join(SRC, 'setup', name + '.tex'), encoding='utf-8').read()
        if st:
            s = s.replace('\\begin{table}[t]', '\\begin{table*}[t]').replace('\\end{table}', '\\end{table*}')
        s = s.replace('\\centering\n', '\\centering\n\\small\n', 1)
        s = sane(s)
        s = '%% Copy: copied from final_report_materials/tables/setup/%s.tex, only table%s and Unicode symbols changed; original file untouched\n' % (name, '→table*' if st else '') + s
        open(os.path.join(OUT, name + '.tex'), 'w', encoding='utf-8').write(s)


def main():
    os.makedirs(OUT, exist_ok=True)
    full_table('tab_e1_full_v1', 'Exp. 1 (same event) full test-set metrics: 10 test runs for each of six events, all 168 time steps', 'tab:e1-full')
    full_table('tab_e2_full_v1', 'Exp. 2 (cross-event, 6-fold leave-one-out) full test-set metrics: each row is the held-out event of that fold', 'tab:e2-full')
    main_table(); e3_tables(); setup_tables()
    for f in sorted(os.listdir(OUT)):
        print('  ', os.path.join('final_report_materials/draft/latex_zh/tables', f))


if __name__ == '__main__':
    main()
