#!/usr/bin/env python3
"""71_latex_tables_zh_v2.py -- table .tex files for the Chinese v2 draft. Writes only final_report_materials/draft/latex_zh_v2/tables/.

Does not touch code/70 or latex_zh/ (v1). Redone for the user's comments 5-8 of 2026-09-20:

Item 5 Table 1 (events): drop the "rainfall product" column; merge year into the hurricane column; keep a one-sentence note; drop scenario count / Usage / source paragraph.
                     6 -> 4 columns, now a **single-column table** (no longer takes a two-column slot).
Item 6 Table 2 (scenarios): merge symbols into the factor column; "applies to" keeps only the object name, no formula (formula moved to a display equation in the text); one-sentence note;
                     drop the numbering order and s001/s081.
Item 7 Table 3 (hyperparameters): was single-column 2 columns without wrapping, squeezed into the right column -- now `@{}l p{}@{}` with wrapping, **still single-column** (no two-column slot).
Item 8 Tables 4 / 6 / 7 truncated: use **grouped two-row headers + short column names + \\small / \\footnotesize**
                     (no resizebox, no pdflscape). Table 4: single-step RMSE{Exp. 1, Exp. 2} / Persistence /
                     rollout RMSE{...} / single-step CSI 0.1{...}; Tables 6/7: active cells{MAE, RMSE, CSI 0.1, CSI 0.3} / land cells{...}.

Numbers are never changed; all are read from final_report_materials/tables/*.csv; the text of the three setup tables comes from
the finalized content of final_report_materials/tables/setup/*.tex; only the layout changes.

Usage: python3 code/71_latex_tables_zh_v2.py
"""
import os, csv

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'final_report_materials', 'tables')
OUT = os.path.join(ROOT, 'final_report_materials', 'draft', 'latex_zh_v2', 'tables')
def rcsv(n):
    for d in (SRC, os.path.join(SRC, 'setup')):        # experiment tables in tables/, setup tables in tables/setup/
        p = os.path.join(d, n + '.csv')
        if os.path.isfile(p):
            return list(csv.DictReader(open(p, encoding='utf-8')))
    raise SystemExit('Cannot find %s.csv' % n)
esc = lambda t: str(t).replace('%', r'\%').replace('_', r'\_').replace('&', r'\&')


def head(f, name, star, size, caption, label, cols):
    env = 'table*' if star else 'table'
    f.write('%% %s -- generated by code/71_latex_tables_zh_v2.py; numbers unchanged, layout only\n' % name)
    f.write('\\begin{%s}[t]\n\\centering\n%s\n\\caption{%s}\n\\label{%s}\n' % (env, size, caption, label))
    f.write('\\begin{tabular}{%s}\n\\toprule\n' % cols)


def tail(f, star, note=None):
    f.write('\\bottomrule\n\\end{tabular}\n')
    if note:
        f.write('\\\\[2pt]\n\\begin{minipage}{\\linewidth}\\footnotesize %s\\end{minipage}\n' % esc(note))
    f.write('\\end{%s}\n' % ('table*' if star else 'table'))


# ---------------------------------------------------------------- Table 1 events (single column)
def t_events():
    rows = rcsv('tab_events_v1')
    rows.sort(key=lambda r: int(r['year']))
    with open(os.path.join(OUT, 'tab_events_v1.tex'), 'w', encoding='utf-8') as f:
        head(f, 'tab_events_v1', False, r'\footnotesize',
             'Simulation windows of the six events (UTC)', 'tab:events', '@{}llll@{}')
        f.write('Hurricane & Simulation start & Main-period start & Simulation end \\\\\n\\midrule\n')
        for r in rows:
            f.write('%s (%s) & %s & %s & %s \\\\\n' % (r['hurricane'], r['year'],
                    r['start_utc'], r['event_start_utc'], r['end_utc']))
        tail(f, False, 'Each event spans 10 days = 72 h spin-up + 168 h main period; surrogate target times are t = 73...240 h.')


# ---------------------------------------------------------------- Table 2 scenarios (single column)
def t_scenarios():
    rows = [('Rainfall scale $\\beta$', '0.70 / 1.00 / 1.30', 'Gridded rainfall intensity over the whole domain'),
            ('Non-tidal water-level residual scale $\\alpha$', '0.80 / 1.00 / 1.20', 'Non-tidal residual of Mayport water level'),
            ('Low-frequency discharge scale $\\gamma$', '0.75 / 1.00 / 1.25', 'Low-frequency component of Acosta discharge'),
            ('Rainfall time shift $\\tau$ (h)', '$-6$ / 0 / $+6$', 'Timing (phase) of the rainfall field')]
    with open(os.path.join(OUT, 'tab_scenarios_v1.tex'), 'w', encoding='utf-8') as f:
        head(f, 'tab_scenarios_v1', False, r'\footnotesize',
             'Four perturbation factors of the compound-forcing scenarios', 'tab:scenarios', '@{}lll@{}')
        f.write('Factor & Values & Applies to \\\\\n\\midrule\n')
        for a, b, c in rows:
            f.write('%s & %s & %s \\\\\n' % (a, b, c))
        tail(f, False, 'The full factorial of the four factors gives 81 scenarios; the baseline scenario s041 has $\\alpha=\\beta=\\gamma=1$, $\\tau=0$.')


# ---------------------------------------------------------------- Table 3 hyperparameters (single column, p{} wrapping)
def t_hparams():
    rows = rcsv('tab_unet_hparams_v3')
    sec = {'': [], 'Pre-training': [], 'Fine-tuning': []}
    for r in rows:
        sec[r['section']].append((r['item'], r['setting']))
    fix = lambda s: (s.replace('≥', '$\\geq$').replace('−', '$-$').replace('×', '$\\times$')
                      .replace('→', '$\\to$').replace('≤', '$\\leq$'))
    with open(os.path.join(OUT, 'tab_unet_hparams_v3.tex'), 'w', encoding='utf-8') as f:
        head(f, 'tab_unet_hparams_v3', False, r'\footnotesize',
             'Training settings and hyperparameters of U-Net v1', 'tab:unet-hparams',
             '@{}l p{0.60\\linewidth}@{}')
        f.write('Item & Setting \\\\\n\\midrule\n')
        for it, st in sec['']:
            f.write('%s & %s \\\\\n' % (esc(it), fix(esc(st))))
        f.write('\\midrule\n\\textit{Pre-training} & \\\\\n')
        for it, st in sec['Pre-training']:
            f.write('%s & %s \\\\\n' % (esc(it), fix(esc(st))))
        f.write('\\midrule\n\\textit{Fine-tuning (Exp. 3)} & \\\\\n')
        for it, st in sec['Fine-tuning']:
            f.write('%s & %s \\\\\n' % (esc(it), fix(esc(st))))
        tail(f, False)


# ---------------------------------------------------------------- Table 4 main-text table (grouped header)
def t_main():
    rows = rcsv('tab_e12_main_v1')
    with open(os.path.join(OUT, 'tab_e12_main_v1.tex'), 'w', encoding='utf-8') as f:
        head(f, 'tab_e12_main_v1', True, r'\small',
             'Main metrics of Exp. 1 (same event) and Exp. 2 (cross-event, 6-fold leave-one-out). RMSE in m, all computed on active cells',
             'tab:e12-main', '@{}l rr c rr c rr@{}')
        f.write('& \\multicolumn{2}{c}{Single-step RMSE} & Persistence & \\multicolumn{2}{c}{Rollout RMSE}'
                ' & & \\multicolumn{2}{c}{Single-step CSI 0.1} \\\\\n')
        f.write('\\cmidrule(lr){2-3}\\cmidrule(lr){5-6}\\cmidrule(lr){8-9}\n')
        f.write('Event & Exp. 1 & Exp. 2 & RMSE & Exp. 1 & Exp. 2 & & Exp. 1 & Exp. 2 \\\\\n\\midrule\n')
        for r in rows:
            b = (lambda v: '\\textbf{%s}' % v) if r['event'] == 'All' else (lambda v: v)
            f.write(' & '.join([b(r['event']),
                                b('%.4f' % float(r['single_rmse_exp1'])), b('%.4f' % float(r['single_rmse_exp2'])),
                                b('%.4f' % float(r['persistence_rmse'])),
                                b('%.4f' % float(r['rollout_rmse_exp1'])), b('%.4f' % float(r['rollout_rmse_exp2'])),
                                '', b('%.3f' % float(r['single_csi01_exp1'])), b('%.3f' % float(r['single_csi01_exp2']))])
                    + ' \\\\\n')
        tail(f, True, 'Each Exp. 2 row is the result with that event held out. Persistence is model-independent and shared by both experiments.'
                      ' Each row pools that event\'s 10 test runs × 168 time steps; the total row pools 60 runs.')


# ---------------------------------------------------------------- Tables 6 / 7 full tables (grouped header)
def t_full(name, caption, label):
    rows = rcsv(name)
    with open(os.path.join(OUT, name + '.tex'), 'w', encoding='utf-8') as f:
        head(f, name, True, r'\footnotesize', caption, label,
             '@{}ll rrrr c rrrr@{}')
        f.write('& & \\multicolumn{4}{c}{Active cells} & & \\multicolumn{4}{c}{Land cells} \\\\\n')
        f.write('\\cmidrule(lr){3-6}\\cmidrule(lr){8-11}\n')
        f.write('Event & Mode & MAE & RMSE & CSI 0.1 & CSI 0.3 & & MAE & RMSE & CSI 0.1 & CSI 0.3 \\\\\n\\midrule\n')
        for r in rows:
            b = (lambda v: '\\textbf{%s}' % v) if r['event'] == 'All' else (lambda v: v)
            f.write(' & '.join([b(r['event']), b(r['mode']),
                                b('%.4f' % float(r['mae_active'])), b('%.4f' % float(r['rmse_active'])),
                                b('%.3f' % float(r['csi01_active'])), b('%.3f' % float(r['csi03_active'])), '',
                                b('%.4f' % float(r['mae_land'])), b('%.4f' % float(r['rmse_land'])),
                                b('%.3f' % float(r['csi01_land'])), b('%.3f' % float(r['csi03_land']))]) + ' \\\\\n')
        tail(f, True, 'MAE / RMSE in m; CSI = TP / (TP + FP + FN), wet = h > threshold (0.1 / 0.3 m).'
                      ' 24,467 active cells, 21,933 land cells.')


# ---------------------------------------------------------------- remaining three appendix tables
def t_e3():
    rows = rcsv('tab_e3_strat_v1')
    with open(os.path.join(OUT, 'tab_e3_strat_v1.tex'), 'w', encoding='utf-8') as f:
        head(f, 'tab_e3_strat_v1', True, r'\footnotesize',
             'Exp. 3 stratified results: single-step RMSE (active cells, six-fold mean) and reduction relative to zero-shot', 'tab:e3-strat',
             '@{}l rr@{\\,}r rr@{\\,}r@{}')
        f.write('Stratum & Zero-shot & \\multicolumn{2}{c}{B N=5} & \\multicolumn{2}{c}{B N=10} \\\\\n')
        f.write('\\cmidrule(lr){3-4}\\cmidrule(lr){5-6}\n')
        f.write(' & RMSE & RMSE & Reduction & RMSE & Reduction \\\\\n\\midrule\n')
        for r in rows:
            f.write('%s & %.4f & %.4f & %.1f\\%% & %.4f & %.1f\\%% \\\\\n' %
                    (r['stratum'], float(r['zero_rmse']), float(r['B_N5_rmse']), float(r['B_N5_drop_pct']),
                     float(r['B_N10_rmse']), float(r['B_N10_drop_pct'])))
        tail(f, True, 'The combined forcing level is defined by $(\\alpha,\\beta,\\gamma)$, $\\tau$ is the rainfall time shift; 27 scenarios each.')

    rows = rcsv('tab_e3_forget_v1')
    with open(os.path.join(OUT, 'tab_e3_forget_v1.tex'), 'w', encoding='utf-8') as f:
        head(f, 'tab_e3_forget_v1', True, r'\footnotesize',
             'Exp. 3 source-domain forgetting: single-step RMSE after fine-tuning on the 50 test runs of the other 5 events (active cells, six-fold mean)',
             'tab:e3-forget', '@{}l rrr rrr@{}')
        f.write('& \\multicolumn{3}{c}{B full fine-tuning} & \\multicolumn{3}{c}{B$^{\\prime}$ frozen encoder} \\\\\n')
        f.write('\\cmidrule(lr){2-4}\\cmidrule(lr){5-7}\n')
        f.write('N & RMSE & vs. before & Max single fold & RMSE & vs. before & Max single fold \\\\\n\\midrule\n')
        for r in rows:
            g = lambda k, fmt: (fmt % float(r[k])) if r[k] not in ('', None) else '---'
            f.write('%s & %s & %s & %s & %s & %s & %s \\\\\n' %
                    ('0 (before fine-tuning)' if r['N'] == '0' else r['N'],
                     g('B_rmse', '%.4f'), g('B_change_pct', '$+$%.1f\\%%'), g('B_max_fold_change_pct', '$+$%.1f\\%%'),
                     g('Bp_rmse', '%.4f'), g('Bp_change_pct', '$+$%.1f\\%%'), g('Bp_max_fold_change_pct', '$+$%.1f\\%%')))
        tail(f, True, 'Source domain = the other 5 events used to train that fold, 10 test runs each; before fine-tuning = that fold\'s Exp. 2 model.')

    rows = rcsv('tab_e3_attrs_v1')
    with open(os.path.join(OUT, 'tab_e3_attrs_v1.tex'), 'w', encoding='utf-8') as f:
        head(f, 'tab_e3_attrs_v1', True, r'\footnotesize',
             'Exp. 3 per-event attributes and fine-tuning gain (single-step RMSE, active cells)', 'tab:e3-attrs',
             '@{}l rrr r r rr l@{}')
        f.write('Event & Exp. 1 & Zero-shot & B N=5 & Reduction & Degradation ratio & Wet area & Rainfall & Rainfall product \\\\\n')
        f.write(' & \\multicolumn{3}{c}{RMSE (m)} & & & (km$^2$) & (mm) & \\\\\n\\midrule\n')
        for r in rows:
            f.write('%s & %.4f & %.4f & %.4f & %.1f\\%% & %.2f & %.1f & %.1f & %s \\\\\n' %
                    (r['event'], float(r['exp1_rmse']), float(r['zero_rmse']), float(r['B_N5_rmse']),
                     float(r['B_N5_drop_pct']), float(r['exp2_degrade_ratio']),
                     float(r['wet_km2_testruns_mean']), float(r['rain_mm_81scen_mean']), r['rain_product']))
        tail(f, True, 'Degradation ratio = zero-shot RMSE / Exp. 1 RMSE; wet area is the mean SFINCS land inundated area over that event\'s 10 test runs.')


# ---------------------------------------------------------------- Table 5 architecture table (reuses the v1 copy, font size only)
def t_arch():
    s = open(os.path.join(ROOT, 'final_report_materials', 'draft', 'latex_zh', 'tables',
                          'tab_unet_arch_v2.tex'), encoding='utf-8').read()
    s = s.replace('\\begin{table*}[t]', '\\begin{table}[t]').replace('\\end{table*}', '\\end{table}')
    s = s.replace('\\small\n', '\\footnotesize\n', 1)
    s = s.replace('\\begin{tabular}{lrrl}', '\\begin{tabular}{@{}p{0.46\\linewidth}rrl@{}}')
    s = '%% Layout adapted from latex_zh/tables/tab_unet_arch_v2.tex (table*->table, font size, first-column wrapping); numbers unchanged\n' + s
    open(os.path.join(OUT, 'tab_unet_arch_v2.tex'), 'w', encoding='utf-8').write(s)


UNI = [('≥', r'$\\geq$'), ('≤', r'$\\leq$'), ('≈', r'$\\approx$'), ('×', r'$\\times$'),
       ('→', r'$\\to$'), ('±', r'$\\pm$'), ('−', r'$-$'), ('′', r'$^{\\prime}$'),
       ('²', r'$^{2}$'), ('³', r'$^{3}$'), ('α', r'$\\alpha$'), ('β', r'$\\beta$'),
       ('γ', r'$\\gamma$'), ('τ', r'$\\tau$'), ('…', r'\\ldots{}')]


def sanitize_all():
    """Times (Type1) lacks these characters and XeLaTeX would show boxes. Data rows must be covered too, so clean everything after generation."""
    for fn in os.listdir(OUT):
        f = os.path.join(OUT, fn)
        t = open(f, encoding='utf-8').read()
        for a, b in UNI:
            t = t.replace(a, b)
        open(f, 'w', encoding='utf-8').write(t)


def main():
    os.makedirs(OUT, exist_ok=True)
    t_events(); t_scenarios(); t_hparams(); t_main()
    t_full('tab_e1_full_v1', 'Exp. 1 (same event) full test-set metrics', 'tab:e1-full')
    t_full('tab_e2_full_v1', 'Exp. 2 (cross-event, 6-fold leave-one-out) full test-set metrics; each row is that fold\'s held-out event', 'tab:e2-full')
    t_e3(); t_arch(); sanitize_all()
    star = sum(1 for f in os.listdir(OUT) if 'table*' in open(os.path.join(OUT, f), encoding='utf-8').read())
    print('  %d tables written to latex_zh_v2/tables/; %d two-column table*, %d single-column table'
          % (len(os.listdir(OUT)), star, len(os.listdir(OUT)) - star))


if __name__ == '__main__':
    main()
