#!/usr/bin/env python3
"""72_latex_tables_zh_v3.py -- table .tex files for v3 of the report (originally the Chinese version). Writes only final_report_materials/draft/latex_zh_v3/tables/.

Does not touch code/70 or latex_zh/ (v1). Redone according to the user's review comments 5-8 of 2026-09-20:

Comment 5 Table 1 (events): drop the "rainfall product" column; merge the year into the hurricane column; keep a single-sentence note; drop the scenario count / Usage / sources paragraph.
                     Columns 6→4, now a **single-column table** (no longer takes a two-column slot).
Comment 6 Table 2 (scenarios): symbols merged into the factor column; "applied to" keeps only the object name, no formula (formula moved to a display equation in the text); single-sentence note;
                     drop the numbering order and s001/s081.
Comment 7 Table 3 (hyperparameters): previously single-column, 2 columns without wrapping, squeezed into the right column -- now `@{}l p{}@{}` with wrapping, **still single-column** (no two-column slot).
Comment 8 Tables 4 / 6 / 7 truncated: now use **grouped two-row headers + short column names + \\small / \\footnotesize**
                     (no resizebox, no pdflscape). Table 4: single-step RMSE{Exp 1, Exp 2} / Persistence /
                     rollout RMSE{...} / single-step CSI 0.1{...}; Tables 6/7: active cells{MAE, RMSE, CSI 0.1, CSI 0.3} / land cells{...}.

No numbers are changed; all are read from final_report_materials/tables/*.csv; the text of the three setup tables comes from
the finalized final_report_materials/tables/setup/*.tex, only the layout changes.

Usage: python3 code/72_latex_tables_zh_v3.py
"""
import os, csv, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'final_report_materials', 'tables')
OUT = os.path.join(ROOT, 'final_report_materials', 'draft', 'latex_zh_v3', 'tables')
def rcsv(n):
    for d in (SRC, os.path.join(SRC, 'setup')):        # experiment tables in tables/, setup tables in tables/setup/
        p = os.path.join(d, n + '.csv')
        if os.path.isfile(p):
            return list(csv.DictReader(open(p, encoding='utf-8')))
    raise SystemExit('cannot find %s.csv' % n)
esc = lambda t: str(t).replace('%', r'\%').replace('_', r'\_').replace('&', r'\&')


def head(f, name, star, size, caption, label, cols, place='t'):
    env = 'table*' if star else 'table'
    f.write('%% %s -- generated by code/72_latex_tables_zh_v3.py; numbers unchanged, layout only\n' % name)
    f.write('\\begin{%s}[%s]\n\\centering\n%s\n\\caption{%s}\n\\label{%s}\n' % (env, place, size, caption, label))
    f.write('\\begin{tabular}{%s}\n\\toprule\n' % cols)


def tail(f, star, note=None):
    f.write('\\bottomrule\n\\end{tabular}\n')
    if note:
        # the float's \centering leaks into the minipage, centring the note and indenting the second line; hence an explicit \raggedright.
        f.write('\\par\\vspace{2pt}\n\\begin{minipage}{\\linewidth}\\footnotesize\\raggedright %s\\end{minipage}\n' % esc(note))
    f.write('\\end{%s}\n' % ('table*' if star else 'table'))


# ---------------------------------------------------------------- Table 1 events (single column)
def t_events():
    rows = rcsv('tab_events_v1')
    rows.sort(key=lambda r: int(r['year']))
    with open(os.path.join(OUT, 'tab_events_v1.tex'), 'w', encoding='utf-8') as f:
        head(f, 'tab_events_v1', False, r'\footnotesize',
             'Simulation windows of the six events (UTC)', 'tab:events', '@{}llll@{}')
        f.write('Hurricane & Sim. start & Event start & Sim. end \\\\\n\\midrule\n')
        for r in rows:
            f.write('%s (%s) & %s & %s & %s \\\\\n' % (r['hurricane'], r['year'],
                    r['start_utc'], r['event_start_utc'], r['end_utc']))
        tail(f, False, 'Surrogate target times are t = 73…240 h.')


# ---------------------------------------------------------------- Table 2 scenarios (single column)
def t_scenarios():
    rows = [('Rainfall scale $\\beta$', '0.70 / 1.00 / 1.30', 'per-cell rainfall intensity over the whole domain'),
            ('Non-tidal residual scale $\\alpha$', '0.80 / 1.00 / 1.20', 'non-tidal residual of Mayport water level'),
            ('Low-frequency discharge scale $\\gamma$', '0.75 / 1.00 / 1.25', 'low-frequency component of Acosta discharge'),
            ('Rainfall time shift $\\tau$ (h)', '$-6$ / 0 / $+6$', 'time phase of the rainfall field')]
    with open(os.path.join(OUT, 'tab_scenarios_v1.tex'), 'w', encoding='utf-8') as f:
        head(f, 'tab_scenarios_v1', False, r'\footnotesize',
             'The four perturbation factors of the compound-forcing scenarios', 'tab:scenarios', '@{}lll@{}')
        f.write('Factor & Values & Applied to \\\\\n\\midrule\n')
        for a, b, c in rows:
            f.write('%s & %s & %s \\\\\n' % (a, b, c))
        tail(f, False, 'The full combination of the four factors gives 81 scenarios; the baseline scenario s041 has $\\alpha=\\beta=\\gamma=1$, $\\tau=0$.')


# ---------------------------------------------------------------- Table 3 hyperparameters (single column, p{} wrapping)
def t_hparams():
    rows = rcsv('tab_unet_hparams_v3')
    sec = {'': [], 'Pre-training': [], 'Fine-tuning': []}
    for r in rows:
        sec[r['section']].append((r['item'], r['setting']))
    fix = lambda s: (s.replace('≥', '$\\geq$').replace('−', '$-$').replace('×', '$\\times$')
                      .replace('→', '$\\to$').replace('≤', '$\\leq$'))
    with open(os.path.join(OUT, 'tab_unet_hparams_v3.tex'), 'w', encoding='utf-8') as f:
        head(f, 'tab_unet_hparams_v3', False, r'\footnotesize',
             'Training settings and hyperparameters of the U-Net', 'tab:unet-hparams',
             '@{}l p{0.60\\linewidth}@{}')
        f.write('Item & Setting \\\\\n\\midrule\n')
        for it, st in sec['']:
            f.write('%s & %s \\\\\n' % (esc(it), fix(esc(st))))
        f.write('\\midrule\n\\textit{Pretraining} & \\\\\n')
        for it, st in sec['Pre-training']:
            f.write('%s & %s \\\\\n' % (esc(it), fix(esc(st))))
        f.write('\\midrule\n\\textit{Fine-tuning (Experiment 3)} & \\\\\n')
        for it, st in sec['Fine-tuning']:
            f.write('%s & %s \\\\\n' % (esc(it), fix(esc(st))))
        tail(f, False)


# ---------------------------------------------------------------- Table 4 main-text table (grouped header)
def t_main():
    """Comment 7: after dropping the two CSI columns (numbers now given in the text) 6 columns remain, single column;
    the header uses "Baseline" instead of the too-wide Persistence, and tabcolsep is narrowed."""
    rows = rcsv('tab_e12_main_v1')
    with open(os.path.join(OUT, 'tab_e12_main_v1.tex'), 'w', encoding='utf-8') as f:
        f.write('%% tab_e12_main_v1 -- generated by code/72_latex_tables_zh_v3.py; numbers unchanged\n')
        f.write('\\begin{table}[t]\n\\centering\n\\footnotesize\n\\setlength{\\tabcolsep}{3pt}\n')
        f.write('\\caption{Main metrics for Experiment 1 (same event) and Experiment 2 (cross-event, 6-fold leave-one-out). RMSE in m, all on active cells}\n')
        f.write('\\label{tab:e12-main}\n\\begin{tabular}{@{}l rr r rr@{}}\n\\toprule\n')
        f.write('& \\multicolumn{2}{c}{Single-step RMSE} & Baseline & \\multicolumn{2}{c}{Rollout RMSE} \\\\\n')
        f.write('\\cmidrule(lr){2-3}\\cmidrule(lr){5-6}\n')
        f.write('Event & Exp. 1 & Exp. 2 & RMSE & Exp. 1 & Exp. 2 \\\\\n\\midrule\n')
        for r in rows:
            b = (lambda v: '\\textbf{%s}' % v) if r['event'] == 'All' else (lambda v: v)
            f.write(' & '.join([b(r['event']),
                                b('%.4f' % float(r['single_rmse_exp1'])), b('%.4f' % float(r['single_rmse_exp2'])),
                                b('%.4f' % float(r['persistence_rmse'])),
                                b('%.4f' % float(r['rollout_rmse_exp1'])), b('%.4f' % float(r['rollout_rmse_exp2']))])
                    + ' \\\\\n')
        f.write('\\bottomrule\n\\end{tabular}\n')
        f.write('\\par\\vspace{2pt}\n\\begin{minipage}{\\linewidth}\\footnotesize\\raggedright '
                'Baseline = persistence, i.e. the SFINCS ground truth at t-1 used as the prediction for t; model-independent and shared by both experiments. '
                'Each Experiment 2 row is the result with that event held out. Each row pools that event\'s 10 test runs × 168 times; the total row pools 60 runs.'
                '\\end{minipage}\n\\end{table}\n')


# ---------------------------------------------------------------- Tables 6 / 7 full tables (grouped header)
def t_full(name, caption, label):
    rows = rcsv(name)
    with open(os.path.join(OUT, name + '.tex'), 'w', encoding='utf-8') as f:
        head(f, name, True, r'\footnotesize', caption, label,
             '@{}ll rrrr c rrrr@{}', place='htbp')
        f.write('& & \\multicolumn{4}{c}{Active cells} & & \\multicolumn{4}{c}{Land cells} \\\\\n')
        f.write('\\cmidrule(lr){3-6}\\cmidrule(lr){8-11}\n')
        f.write('Event & Mode & MAE & RMSE & CSI 0.1 & CSI 0.3 & & MAE & RMSE & CSI 0.1 & CSI 0.3 \\\\\n\\midrule\n')
        for r in rows:
            b = (lambda v: '\\textbf{%s}' % v) if r['event'] == 'All' else (lambda v: v)
            f.write(' & '.join([b(r['event']), b(r['mode']),
                                b('%.4f' % float(r['mae_active'])), b('%.4f' % float(r['rmse_active'])),
                                b('%.3f' % float(r['csi01_active'])), b('%.3f' % float(r['csi03_active'])), '',
                                b('%.4f' % float(r['mae_land'])), b('%.4f' % float(r['rmse_land'])),
                                b('%.3f' % float(r['csi01_land'])), b('%.3f' % float(r['csi03_land']))]) + ' \\\\\n')
        tail(f, True, 'MAE / RMSE in m; CSI = TP / (TP + FP + FN), wet = h > threshold (0.1 / 0.3 m). '
                      '24,467 active cells, 21,933 land cells.')


# ---------------------------------------------------------------- the remaining three appendix tables
def t_e3():
    rows = rcsv('tab_e3_strat_v1')
    with open(os.path.join(OUT, 'tab_e3_strat_v1.tex'), 'w', encoding='utf-8') as f:
        head(f, 'tab_e3_strat_v1', True, r'\footnotesize',
             'Experiment 3 stratified results: single-step RMSE (active cells, six-fold mean) and reduction relative to zero-shot', 'tab:e3-strat',
             '@{}l rr@{\\,}r rr@{\\,}r@{}')
        f.write('Stratum & Zero-shot & \\multicolumn{2}{c}{B N=5} & \\multicolumn{2}{c}{B N=10} \\\\\n')
        f.write('\\cmidrule(lr){3-4}\\cmidrule(lr){5-6}\n')
        f.write(' & RMSE & RMSE & Reduction & RMSE & Reduction \\\\\n\\midrule\n')
        for r in rows:
            f.write('%s & %.4f & %.4f & %.1f\\%% & %.4f & %.1f\\%% \\\\\n' %
                    (r['stratum'], float(r['zero_rmse']), float(r['B_N5_rmse']), float(r['B_N5_drop_pct']),
                     float(r['B_N10_rmse']), float(r['B_N10_drop_pct'])))
        tail(f, True, 'The compound forcing level is defined by $(\\alpha,\\beta,\\gamma)$, $\\tau$ is the rainfall time shift; 27 scenarios each.')

    rows = rcsv('tab_e3_forget_v1')
    with open(os.path.join(OUT, 'tab_e3_forget_v1.tex'), 'w', encoding='utf-8') as f:
        head(f, 'tab_e3_forget_v1', True, r'\footnotesize',
             'Experiment 3 source-domain forgetting: single-step RMSE on the 50 test runs of the other 5 events after fine-tuning (active cells, six-fold mean)',
             'tab:e3-forget', '@{}l rrr rrr@{}', place='htbp')
        f.write('& \\multicolumn{3}{c}{B, full fine-tuning} & \\multicolumn{3}{c}{B$^{\\prime}$, frozen encoder} \\\\\n')
        f.write('\\cmidrule(lr){2-4}\\cmidrule(lr){5-7}\n')
        f.write('N & RMSE & vs.\\ before & Worst fold & RMSE & vs.\\ before & Worst fold \\\\\n\\midrule\n')
        for r in rows:
            g = lambda k, fmt: (fmt % float(r[k])) if r[k] not in ('', None) else '---'
            f.write('%s & %s & %s & %s & %s & %s & %s \\\\\n' %
                    ('0 (before fine-tuning)' if r['N'] == '0' else r['N'],
                     g('B_rmse', '%.4f'), g('B_change_pct', '$+$%.1f\\%%'), g('B_max_fold_change_pct', '$+$%.1f\\%%'),
                     g('Bp_rmse', '%.4f'), g('Bp_change_pct', '$+$%.1f\\%%'), g('Bp_max_fold_change_pct', '$+$%.1f\\%%')))
        tail(f, True, 'Source domain = the other 5 events used for training in that fold, 10 test runs each; before fine-tuning = the Experiment 2 model of that fold.')

    rows = rcsv('tab_e3_attrs_v1')
    with open(os.path.join(OUT, 'tab_e3_attrs_v1.tex'), 'w', encoding='utf-8') as f:
        head(f, 'tab_e3_attrs_v1', True, r'\footnotesize',
             'Experiment 3 per-event attributes and fine-tuning gains (single-step RMSE, active cells)', 'tab:e3-attrs',
             '@{}l r r r r r l@{}', place='htbp')
        f.write('Event & B N=5 & Reduction & Degrad. factor & Wet area & Total rainfall & Rainfall product \\\\\n')
        f.write(' & RMSE (m) & & & (km$^2$) & (mm) & \\\\\n\\midrule\n')
        for r in rows:
            f.write('%s & %.4f & %.1f\\%% & %.2f & %.1f & %.1f & %s \\\\\n' %
                    (r['event'], float(r['B_N5_rmse']), float(r['B_N5_drop_pct']),
                     float(r['exp2_degrade_ratio']),
                     float(r['wet_km2_testruns_mean']), float(r['rain_mm_81scen_mean']), r['rain_product']))
        tail(f, True, 'Values for "Experiment 1" and "zero-shot" are in the two single-step RMSE columns of Table~\\ref{tab:e12-main}. '
                      'Degradation factor = zero-shot RMSE / Experiment 1 RMSE; wet area is the mean SFINCS flooded land area over the event\'s 10 test runs.')


# ---------------------------------------------------------------- Table 5 architecture (reuses the v1 copy, only the font size changes)
def t_arch():
    s = open(os.path.join(ROOT, 'final_report_materials', 'draft', 'latex_zh', 'tables',
                          'tab_unet_arch_v2.tex'), encoding='utf-8').read()
    s = s.replace('\\begin{table*}[t]', '\\begin{table}[htbp]').replace('\\end{table*}', '\\end{table}')
    s = s.replace('U-Net v1 architecture', 'U-Net architecture')
    s = s.replace('\\small\n', '\\footnotesize\n', 1)
    s = s.replace('\\begin{tabular}{lrrl}', '\\begin{tabular}{@{}p{0.46\\linewidth}rrl@{}}')
    # Comment 1: this table reuses the old note style of the v1 copy; switch it to \par\vspace + raggedright as well
    s = s.replace('\\\\[2pt]\n\\begin{minipage}{\\linewidth}\\footnotesize',
                  '\\par\\vspace{2pt}\n\\begin{minipage}{\\linewidth}\\footnotesize\\raggedright')
    s = '%% re-laid-out from latex_zh/tables/tab_unet_arch_v2.tex (table*→table, font size, first-column wrapping); numbers unchanged\n' + s
    open(os.path.join(OUT, 'tab_unet_arch_v2.tex'), 'w', encoding='utf-8').write(s)


UNI = [('≥', r'$\geq$'), ('≤', r'$\leq$'), ('≈', r'$\approx$'), ('×', r'$\times$'),
       ('→', r'$\to$'), ('±', r'$\pm$'), ('−', r'$-$'), ('′', r'$^{\prime}$'),
       ('²', r'$^{2}$'), ('³', r'$^{3}$'), ('α', r'$\alpha$'), ('β', r'$\beta$'),
       ('γ', r'$\gamma$'), ('τ', r'$\tau$'), ('…', r'\ldots{}')]
# 2026-09-20 fix: these were previously written as r'$\\times$' etc. (two backslashes in a raw string), but the replacement uses str.replace,
#   which does not unescape, so the output contained literal \\times / \\ldots / \\tau / \\prime and the PDF showed the command text.


def sanitize_all():
    """Times (Type1) lacks these characters and XeLaTeX would show boxes. Data rows must be covered too, so everything is sanitized after generation."""
    for fn in os.listdir(OUT):
        f = os.path.join(OUT, fn)
        t = open(f, encoding='utf-8').read()
        for a, b in UNI:
            t = t.replace(a, b)
        open(f, 'w', encoding='utf-8').write(t)


def main():
    os.makedirs(OUT, exist_ok=True)
    t_events(); t_scenarios(); t_hparams(); t_main()
    t_full('tab_e1_full_v1', 'Experiment 1 (same event) full test-set metrics', 'tab:e1-full')
    t_full('tab_e2_full_v1', 'Experiment 2 (cross-event, 6-fold leave-one-out) full test-set metrics; each row is the held-out event of that fold', 'tab:e2-full')
    t_e3(); t_arch(); sanitize_all()
    # Comment 9: the 3 main-text tables use [t] (top of the page after first reference); the 7 appendix tables all use [htbp] so they flow with the text instead of each taking a page
    MAIN = {'tab_events_v1', 'tab_scenarios_v1', 'tab_e12_main_v1'}
    for fn in os.listdir(OUT):
        f = os.path.join(OUT, fn); t = open(f, encoding='utf-8').read()
        want = 't' if fn[:-4] in MAIN else 'htbp'
        t = re.sub(r'(\\begin\{table\*?\})\[[a-z!]*\]', r'\1[' + want + ']', t)
        open(f, 'w', encoding='utf-8').write(t)
    star = sum(1 for f in os.listdir(OUT) if 'table*' in open(os.path.join(OUT, f), encoding='utf-8').read())
    print('  %d tables written to latex_zh_v3/tables/; %d two-column table*, %d single-column table'
          % (len(os.listdir(OUT)), star, len(os.listdir(OUT)) - star))


if __name__ == '__main__':
    main()
